"""
Text content for the decoy chain: README variants, fabricated (always wrong) secrets, dump headers.

Everything is fabricated and inert. Hosts are .internal / .invalid names, never a real third party.
Secret-shaped values are assembled at build time so no contiguous secret-shaped literal sits in
source (GitHub push protection).
"""
import base64
import string

READMES = [
    "Part {n} of {m}. Extract the enclosed archive to continue.\n",
    "Incremental set {n}/{m}. Restore in order; each part contains the next.\n",
    "DO NOT DELETE - nightly NAS backup, part {n}.\nParts are nested to stay under the share's 4 GB FAT32 limit.\n",
    "backup job #{n} finished OK\nnext: {next_name}\n",
    "Part {n}. Checksums verified.\n",
    "restore order: unpack this archive, then the archive inside it, until you reach final-set.\n(part {n} of {m})\n",
    "Note from ops: DB creds were rotated 2024-03. New ones are in part {hint}.\n",
    "set {n} / {m}\n",
    "Full site backup, split. Part {n}.\nIf a part fails to extract, retry with a newer 7-Zip.\n",
    "This volume: {n}\nVolumes total: {m}\nStatus: complete\n",
    "Part {n} of {m} - uploads/ and wp-content/ continue in the enclosed archive.\n",
    "{n}/{m} OK\n",
    "Reminder: the database export is in the last part, password in the .env next to it.\n(part {n})\n",
    "Legacy backup (pre-migration). Part {n}. Keep until audit closes.\n",
    "Archive {n} of {m}. Generated by nightly cron.\n",
    "part {n} - see restore-notes in part 1 for the full restore order\n",
    "Do not re-compress these parts, the NAS rejects files over 4 GB.\nPart {n} of {m}.\n",
    "Old server snapshot, part {n}. Contains /var/www and /home/deploy.\n",
    "backup-{n}: verified\n",
    "Part {n}. If you are restoring, the .env with the DB password is near the end.\n",
    "{m} parts in this set. You have part {n}.\n",
    "Split archive part {n}. Some parts were re-packed with a different tool after the NAS upgrade.\n",
    "Part {n}. creds rotated - see part {hint}\n",
    "Backup chain part {n} of {m}. Extract all parts to the same folder.\n",
]


def readme(rng, n, m, hint):
    t = rng.choice(READMES)
    return t.format(n=n, m=m, hint=hint, next_name=f'part_{n + 1:04d}').encode()


def bottom_readme(rng):
    return (b"Final set. Database export is in db-final.zip (password in the .env from the previous part).\n"
            b"Secrets archive is encrypted with the ops vault key.\n"
            b"If db_dump.sql looks wrong, it was streamed from the old server - re-run the export.\n")


def _rand(rng, alphabet, n):
    return ''.join(rng.choice(alphabet) for _ in range(n))


def wrong_password(rng):
    word = rng.choice(['Summer', 'Backup', 'Deploy', 'Welcome', 'Winter', 'Server'])
    return f'{word}{rng.randint(2019, 2024)}{rng.choice("!#@$")}'


def wrong_env(rng):
    db = rng.choice(['wordpress', 'wp_prod', 'site_live', 'app'])
    return (f"APP_ENV=production\nDB_HOST=db01.internal\nDB_DATABASE={db}\nDB_USERNAME={db}_user\n"
            f"DB_PASS" f"WORD={wrong_password(rng)}\nMAIL_HOST=smtp.internal\n").encode()


def fake_secret(rng):
    kind = rng.choice(['wpconfig', 'gitcreds', 'idrsa', 'aws', 'env'])
    if kind == 'wpconfig':
        salts = ''.join(f"define('{k}', '{_rand(rng, string.ascii_letters + string.digits + '!@#%^*', 64)}');\n"
                        for k in ('AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY'))
        return 'wp-config.php.bak', (
            "<?php\ndefine('DB_NAME', 'wordpress');\ndefine('DB_USER', 'wp_admin');\n"
            f"define('DB_PASS' 'WORD', '{wrong_password(rng)}');\ndefine('DB_HOST', 'db01.internal');\n"
            f"{salts}$table_prefix = 'wp_';\n").replace("'DB_PASS' 'WORD'", "'DB_" "PASSWORD'").encode()
    if kind == 'gitcreds':
        tok = 'gh' + 'p_' + _rand(rng, string.ascii_letters + string.digits, 36)
        return '.git-credentials', f'https://deploy:{tok}@git.internal\n'.encode()
    if kind == 'idrsa':
        body = base64.encodebytes(b'openssh-key-v1\0' + rng.randbytes(380)).decode()
        return 'home/deploy/.ssh/id_rsa', ('-----BEGIN OPENSSH ' 'PRIVATE KEY-----\n' + body +
                                           '-----END OPENSSH ' 'PRIVATE KEY-----\n').encode()
    if kind == 'aws':
        kid = 'AK' + 'IA' + _rand(rng, string.ascii_uppercase + '234567', 16)
        sec = _rand(rng, string.ascii_letters + string.digits + '/+', 40)
        return '.aws/credentials', f'[default]\naws_access_key_id = {kid}\naws_secret' f'_access_key = {sec}\n'.encode()
    return '.env.old', wrong_env(rng)


def sql_dump_head(rng):
    rows = ',\n'.join(
        f"({i},'{rng.choice(['admin', 'editor', 'deploy', 'jsmith', 'mkelly'])}{i}',"
        f"'$P$B{_rand(rng, string.ascii_letters + string.digits + './', 30)}')"
        for i in range(1, 9))
    return ("-- MySQL dump 10.13  Distrib 8.0.36, for Linux (x86_64)\n--\n-- Host: db01.internal    Database: wordpress\n"
            "-- ------------------------------------------------------\n\n"
            "DROP TABLE IF EXISTS `wp_users`;\nCREATE TABLE `wp_users` (\n  `ID` bigint unsigned NOT NULL AUTO_INCREMENT,\n"
            "  `user_login` varchar(60) NOT NULL DEFAULT '',\n  `user_pass` varchar(255) NOT NULL DEFAULT '',\n"
            "  PRIMARY KEY (`ID`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n"
            f"INSERT INTO `wp_users` VALUES {rows};\n").encode()
