<?php

declare(strict_types=1);

/*
 * FP-0230 — regenerate the FaviconHash KAT fixture (tests/Support/fixtures/favicon-kat-vectors.php).
 *
 * Dev-bench only. Compiles the INDEPENDENT C reference oracle (oracle.c — a plain uint32_t
 * MurmurHash3 x86_32 port, NOT the PHP 16-bit-split multiply), then emits:
 *   - a1a: 94 varied-length vectors (murmur block edges + base64 76-char wrap), expected from the oracle.
 *   - a1b: >=20 overflow-window vectors selected because a deliberately-buggy un-masked-shift mul32
 *          (the rejected B1 formula) diverges from the correct hash; each expected value is confirmed
 *          against the C oracle. These make the KAT red-on-bug by construction.
 *
 * Usage:  php scripts/dev/favicon/gen-kat-vectors.php   (needs a C compiler: cc/gcc)
 *
 * a1b uses random_bytes to hunt divergences, so re-running produces a different (equally valid) a1b
 * set; the committed fixture is whichever run authored it. a1a is deterministic.
 */

require dirname(__DIR__, 3) . '/vendor/autoload.php';

use Funnypot\Core\Support\FaviconHash;

$here = __DIR__;
$fixture = dirname(__DIR__, 3) . '/tests/Support/fixtures/favicon-kat-vectors.php';
$oracleBin = sys_get_temp_dir() . '/fp0230-oracle-' . getmypid();

$cc = trim((string) shell_exec('command -v cc gcc 2>/dev/null | head -1'));
if ($cc === '') {
    fwrite(STDERR, "error: no C compiler (cc/gcc) found — the independent oracle cannot be built.\n");
    exit(1);
}
passthru(escapeshellarg($cc) . ' -O2 -o ' . escapeshellarg($oracleBin) . ' ' . escapeshellarg($here . '/oracle.c'), $rc);
if ($rc !== 0) {
    fwrite(STDERR, "error: oracle.c failed to compile.\n");
    exit(1);
}
passthru(escapeshellarg($oracleBin) . ' selftest', $rc);
if ($rc !== 0) {
    fwrite(STDERR, "error: oracle self-test failed (murmur3 anchors).\n");
    exit(1);
}

/* ---- deliberately-buggy murmur3: mul32 with the UN-MASKED high partial (rejected B1 bug) ---- */
$buggyMul = static function (int $a, int $b): int {
    $lo = ($a & 0xffff) * $b;
    return ($lo + ((($a >> 16) & 0xffff) * $b << 16)) & 0xffffffff;
};
$rotl = static function (int $x, int $r): int { return (($x << $r) | ($x >> (32 - $r))) & 0xffffffff; };
$buggyHash = static function (string $bytes) use ($buggyMul, $rotl): int {
    $d = FaviconHash::mimeBase64($bytes);
    $h1 = 0; $len = strlen($d); $bl = intdiv($len, 4);
    for ($i = 0; $i < $bl; $i++) { $o = $i * 4;
        $k = ord($d[$o]) | (ord($d[$o+1])<<8) | (ord($d[$o+2])<<16) | (ord($d[$o+3])<<24);
        $k = $buggyMul($k, 0xcc9e2d51); $k = $rotl($k, 15); $k = $buggyMul($k, 0x1b873593);
        $h1 ^= $k; $h1 = $rotl($h1, 13); $h1 = ($buggyMul($h1, 5) + 0xe6546b64) & 0xffffffff;
    }
    $t = $bl * 4; $k = 0; $r = $len & 3;
    if ($r === 3) $k ^= ord($d[$t+2]) << 16;
    if ($r >= 2) $k ^= ord($d[$t+1]) << 8;
    if ($r >= 1) { $k ^= ord($d[$t]); $k = $buggyMul($k, 0xcc9e2d51); $k = $rotl($k, 15); $k = $buggyMul($k, 0x1b873593); $h1 ^= $k; }
    $h1 ^= $len;
    $h1 ^= ($h1 >> 16); $h1 = $buggyMul($h1, 0x85ebca6b); $h1 ^= ($h1 >> 13); $h1 = $buggyMul($h1, 0xc2b2ae35); $h1 ^= ($h1 >> 16);
    $h1 &= 0xffffffff;
    return $h1 > 0x7fffffff ? $h1 - 0x100000000 : $h1;
};

/* ---- A1b hunt ---- */
$diverge = [];
for ($i = 0; $i < 3000000 && count($diverge) < 24; $i++) {
    $b = random_bytes(40 + ($i % 220));
    $c = FaviconHash::hash($b);
    if ($buggyHash($b) !== $c) {
        $diverge[bin2hex($b)] = [$c, $buggyHash($b)];
    }
}
fwrite(STDERR, 'A1b divergent inputs: ' . count($diverge) . "\n");

/* ---- confirm each A1b expected against the independent C oracle ---- */
$desc = [0 => ['pipe', 'r'], 1 => ['pipe', 'w']];
$p = proc_open(escapeshellarg($oracleBin) . ' hexin', $desc, $pipes);
fwrite($pipes[0], implode("\n", array_keys($diverge)) . "\n"); fclose($pipes[0]);
$oracleOut = stream_get_contents($pipes[1]); fclose($pipes[1]); proc_close($p);
$oracle = [];
foreach (explode("\n", trim($oracleOut)) as $l) { if ($l === '') continue; [$hx, $v] = explode(' ', $l); $oracle[$hx] = (int) $v; }
foreach ($diverge as $hex => [$c, $bug]) {
    if (($oracle[$hex] ?? null) !== $c) { fwrite(STDERR, "PANIC: oracle disagrees on $hex\n"); exit(2); }
    if ($bug === $c) { fwrite(STDERR, "PANIC: non-divergent slipped in\n"); exit(2); }
}

/* ---- A1a corpus ---- */
$rows = [];
foreach (explode("\n", trim((string) shell_exec(escapeshellarg($oracleBin)))) as $l) {
    if (!preg_match('/\[([0-9,]*)\],\s*(-?\d+)/', $l, $m)) continue;
    $bytes = $m[1] === '' ? '' : implode('', array_map(static fn ($x) => chr((int) $x), explode(',', $m[1])));
    $rows[] = [bin2hex($bytes), (int) $m[2]];
}
@unlink($oracleBin);

/* ---- emit ---- */
$out  = "<?php\n\ndeclare(strict_types=1);\n\n";
$out .= "// GENERATED by scripts/dev/favicon/gen-kat-vectors.php — DO NOT EDIT BY HAND.\n";
$out .= "// KAT vectors for FaviconHashTest. Every 'expected' is mmh3(base64.encodebytes(bytes))\n";
$out .= "// computed by an INDEPENDENT C reference oracle (scripts/dev/favicon/oracle.c), never by FaviconHash.\n";
$out .= "//   a1a: [hexInput, expectedSignedInt]  — varied lengths (murmur block edges + base64 wrap).\n";
$out .= "//   a1b: [hexInput, expectedSignedInt, buggyValue] — overflow-window inputs on which the\n";
$out .= "//        rejected un-masked-shift mul32 diverges; expected != buggy by selection.\n";
$out .= "return [\n    'a1a' => [\n";
foreach ($rows as [$hex, $exp]) { $out .= "        ['$hex', $exp],\n"; }
$out .= "    ],\n    'a1b' => [\n";
foreach ($diverge as $hex => [$c, $bug]) { $out .= "        ['$hex', $c, $bug],\n"; }
$out .= "    ],\n];\n";
file_put_contents($fixture, $out);
echo 'wrote ' . $fixture . ': a1a=' . count($rows) . ' a1b=' . count($diverge) . "\n";
