<?php

declare(strict_types=1);

namespace Funnypot\Core\Tests;

use Funnypot\Core\Compiler\GeneratedPhp;
use Funnypot\Core\Compiler\SourceTreeStamp;
use Funnypot\Core\Compiler\TemplateGlob;
use PHPUnit\Framework\TestCase;
use RuntimeException;

/**
 * The shared atomic writer (FP-0263 F4) + the glob/stamp helpers it composes with. Every compile-*
 * step emits through GeneratedPhp so the GENERATED header + optional source-tree provenance line
 * are one code path, and a crash mid-write can't leave a torn artifact the runtime would require.
 */
final class GeneratedPhpWriterTest extends TestCase
{
    /** @var string[] */
    private $cleanup = [];

    protected function tearDown(): void
    {
        foreach ($this->cleanup as $p) {
            @unlink($p);
            if (is_dir($p)) {
                @rmdir($p);
            }
        }
        $this->cleanup = [];
    }

    private function tmpFile(string $tag): string
    {
        $p = sys_get_temp_dir() . '/fp-gp-' . $tag . '-' . getmypid() . '-' . uniqid() . '.php';
        $this->cleanup[] = $p;

        return $p;
    }

    public function test_header_and_provenance_line_and_body(): void
    {
        $path = $this->tmpFile('hdr');
        GeneratedPhp::write($path, '`funnypot compile-emulators`', ['a' => 1, 'b' => [2, 3]], str_repeat('a', 64));

        $php = (string) file_get_contents($path);
        self::assertStringStartsWith("<?php\n\ndeclare(strict_types=1);\n", $php);
        self::assertStringContainsString('// GENERATED by `funnypot compile-emulators` — DO NOT EDIT.', $php);
        self::assertStringContainsString('// Provenance: source-tree sha256=' . str_repeat('a', 64) . ' schema=1', $php);

        // Body round-trips to the exact data.
        $data = require $path;
        self::assertSame(['a' => 1, 'b' => [2, 3]], $data);
    }

    public function test_null_provenance_omits_the_line(): void
    {
        $path = $this->tmpFile('noprov');
        GeneratedPhp::write($path, '`funnypot build-manifest`', ['x' => 1], null);

        $php = (string) file_get_contents($path);
        self::assertStringContainsString('// GENERATED by `funnypot build-manifest` — DO NOT EDIT.', $php);
        self::assertStringNotContainsString('Provenance:', $php);
    }

    public function test_atomic_write_leaves_no_tmp_file(): void
    {
        $path = $this->tmpFile('atomic');
        GeneratedPhp::write($path, '`funnypot compile-params`', ['ok' => true], null);

        self::assertFileExists($path);
        $strays = glob($path . '.tmp.*') ?: [];
        self::assertSame([], $strays, 'no .tmp.<pid> file may survive an atomic write');
    }

    public function test_template_glob_rejects_stray_yml(): void
    {
        $dir = sys_get_temp_dir() . '/fp-yml-' . getmypid() . '-' . uniqid();
        mkdir($dir, 0777, true);
        file_put_contents($dir . '/good.yaml', "id: x\n");
        file_put_contents($dir . '/oops.yml', "id: y\n");
        $this->cleanup[] = $dir . '/good.yaml';
        $this->cleanup[] = $dir . '/oops.yml';
        $this->cleanup[] = $dir;

        try {
            TemplateGlob::yaml([$dir]);
            self::fail('expected a RuntimeException for a stray *.yml file');
        } catch (RuntimeException $e) {
            self::assertStringContainsString('oops.yml', $e->getMessage());
        }
    }

    public function test_template_glob_is_sort_string_ordered(): void
    {
        $dir = sys_get_temp_dir() . '/fp-glob-' . getmypid() . '-' . uniqid();
        mkdir($dir, 0777, true);
        foreach (['9-a.yaml', '10-b.yaml', '100-c.yaml', '2-d.yaml'] as $name) {
            file_put_contents($dir . '/' . $name, "id: z\n");
            $this->cleanup[] = $dir . '/' . $name;
        }
        $this->cleanup[] = $dir;

        $files = array_map('basename', TemplateGlob::yaml([$dir]));
        // SORT_STRING: lexicographic, NOT numeric ('10' < '2' as strings).
        self::assertSame(['10-b.yaml', '100-c.yaml', '2-d.yaml', '9-a.yaml'], $files);
    }

    public function test_source_tree_stamp_is_relative_and_input_sensitive(): void
    {
        $root = sys_get_temp_dir() . '/fp-st-' . getmypid() . '-' . uniqid();
        mkdir($root . '/sub', 0777, true);
        $f = $root . '/sub/one.yaml';
        file_put_contents($f, "id: one\n");
        $this->cleanup[] = $f;
        $this->cleanup[] = $root . '/sub';
        $this->cleanup[] = $root;

        $h1 = SourceTreeStamp::hash([$f], $root);
        self::assertMatchesRegularExpression('/^[0-9a-f]{64}$/', $h1);

        // Same bytes at the same repo-relative path from a DIFFERENT absolute root → same stamp
        // (the stamp must not embed the build machine's absolute path).
        $root2 = sys_get_temp_dir() . '/fp-st2-' . getmypid() . '-' . uniqid();
        mkdir($root2 . '/sub', 0777, true);
        $f2 = $root2 . '/sub/one.yaml';
        file_put_contents($f2, "id: one\n");
        $this->cleanup[] = $f2;
        $this->cleanup[] = $root2 . '/sub';
        $this->cleanup[] = $root2;
        self::assertSame($h1, SourceTreeStamp::hash([$f2], $root2), 'stamp must be independent of the absolute root');

        // A byte change flips the stamp.
        file_put_contents($f2, "id: two\n");
        self::assertNotSame($h1, SourceTreeStamp::hash([$f2], $root2), 'a byte change must change the stamp');
    }
}
