<?php

declare(strict_types=1);

namespace Funnypot\Core\Manifest;

use InvalidArgumentException;

/**
 * Renders a reviewable decoy map from the schema-1 manifest — build/CI-time docs tooling only,
 * never a served surface (FP-0004).
 *
 * Pure transformation. It reads no filesystem, template, runtime store, clock, environment, Git
 * or network; every method takes plain arrays and returns bytes. The CLI (`bin/funnypot map`)
 * loads the committed manifest + RouteIntegrity findings and hands them in.
 *
 * The manifest is the sole inventory authority. This class derives only counts, tier mixes, the
 * per-record routes/links already present, a max severity under a fixed order, corpus family/key
 * totals and the single enricher count. It never invents product names, categories, behavior,
 * route precedence, which owned route emitted a link, or any individual corpus member — those
 * stay human-owned in the README taxonomy.
 *
 * Determinism: no input order is observable. Families, records, routes, links, tiers and findings
 * sort by full string keys before rendering, so a shuffled manifest yields byte-identical output.
 * Output carries no timestamp, host path or Git state and ends in exactly one LF.
 *
 * Escaping: Mermaid node ids are generated ASCII ordinals; no manifest text is ever an id, edge or
 * directive. Every data string passes a context-specific encoder (Mermaid entity form / Markdown
 * HTML entity form) after UTF-8/NUL validation, so input cannot close a node, add an edge, break a
 * table column, open a code fence or inject HTML. 7.3-clean (no enums/match/arrow-fns).
 */
final class MapRenderer
{
    /** Fixed relative link the README block and the map header point at. */
    const MAP_PATH = 'docs/DECOY-MAP.md';

    /** README generated-block markers — byte-exact, matched once each, in order. */
    const README_START = '<!-- GENERATED-DECOY-INVENTORY:START -->';
    const README_END = '<!-- GENERATED-DECOY-INVENTORY:END -->';

    /** Input ceilings: bound accidental/adversarial build input far above the real inventory. */
    const MAX_RECORDS = 4096;
    const MAX_ROUTES_PER_RECORD = 1024;
    const MAX_LINKS_PER_RECORD = 1024;
    const MAX_FINDINGS = 4096;
    const MAX_SCALAR_BYTES = 8192;

    /** Severity rank for a record's maximum severity (higher = shown as the record max). */
    private static $severityRank = array(
        'critical' => 5,
        'high' => 4,
        'medium' => 3,
        'low' => 2,
        'info' => 1,
        'unknown' => 0,
    );

    /** Integrity finding display order: fail > warn > accepted > info. */
    private static $findingRank = array(
        'fail' => 3,
        'warn' => 2,
        'accepted' => 1,
        'info' => 0,
    );

    /**
     * Overview or single-family Markdown (Mermaid graph + table + provenance), LF-terminated.
     *
     * @param array<string,mixed>       $manifest schema-1 manifest array
     * @param array<int,array<string,mixed>> $findings RouteIntegrity findings (decoration only)
     * @param string|null               $family   null = overview; else an exact Band-A family
     */
    public function renderMarkdown(array $manifest, array $findings = array(), ?string $family = null): string
    {
        $model = $this->model($manifest, $findings, $family);

        return $family === null
            ? $this->overviewMarkdown($model)
            : $this->familyMarkdown($model);
    }

    /**
     * Raw Mermaid source (no Markdown fence), LF-terminated.
     *
     * @param array<string,mixed>       $manifest
     * @param array<int,array<string,mixed>> $findings
     * @param string|null               $family
     */
    public function renderMermaid(array $manifest, array $findings = array(), ?string $family = null): string
    {
        $model = $this->model($manifest, $findings, $family);

        return $family === null
            ? $this->overviewMermaid($model) . "\n"
            : $this->familyMermaid($model) . "\n";
    }

    /**
     * The README generated-block interior: manifest schema/count/tier facts + a fixed map link.
     * No behavioral prose, no per-family table.
     *
     * @param array<string,mixed> $manifest
     */
    public function renderReadmeInventory(array $manifest): string
    {
        $model = $this->model($manifest, array(), null);
        $c = $model['counts'];

        $lines = array();
        $lines[] = '<!-- Generated by `bin/funnypot map` from resources/compiled/funnypot-manifest.php. Do not edit by hand. -->';
        $lines[] = '';
        $lines[] = '**Decoy inventory** (manifest schema ' . $c['schema'] . ', measurable facts only):';
        $lines[] = '';
        $lines[] = '| Metric | Count |';
        $lines[] = '|---|---|';
        $lines[] = '| Authored decoy records | ' . $c['band_a'] . ' |';
        $lines[] = '| Authored families | ' . $model['family_count'] . ' |';
        foreach ($model['tier_totals'] as $tier => $n) {
            $lines[] = '| &nbsp;&nbsp;tier `' . $this->md($tier) . '` | ' . $n . ' |';
        }
        $lines[] = '| Corpus families (nuclei-inversion) | ' . $c['corpus_families'] . ' |';
        $lines[] = '| Corpus route keys | ' . $c['corpus_keys'] . ' |';
        $lines[] = '| Content enrichers (not route claimers) | ' . $c['enrichers'] . ' |';
        $lines[] = '';
        $lines[] = 'Full visual + per-family drill-downs: [`' . self::MAP_PATH . '`](' . self::MAP_PATH . ') — '
            . 'regenerate with `bin/funnypot map` (`--family=NAME` for one family).';

        return implode("\n", $lines) . "\n";
    }

    /**
     * Replace only the bytes between the two markers with $inventory, preserving every other byte.
     * Requires exactly one start and one end marker in order, with neither token inside $inventory.
     */
    public function replaceReadmeInventory(string $readme, string $inventory): string
    {
        if (strpos($inventory, self::README_START) !== false || strpos($inventory, self::README_END) !== false) {
            throw new InvalidArgumentException('inventory body contains a marker token');
        }
        $this->assertOneMarker($readme, self::README_START);
        $this->assertOneMarker($readme, self::README_END);

        $startPos = strpos($readme, self::README_START);
        $endPos = strpos($readme, self::README_END);
        if ($endPos < $startPos) {
            throw new InvalidArgumentException('README markers are reversed');
        }
        $innerStart = $startPos + strlen(self::README_START);
        if (strpos(substr($readme, $innerStart, $endPos - $innerStart), self::README_START) !== false) {
            throw new InvalidArgumentException('nested START marker');
        }

        $prefix = substr($readme, 0, $innerStart);
        $suffix = substr($readme, $endPos);

        return $prefix . "\n" . $inventory . $suffix;
    }

    /**
     * Validate and normalize the manifest (and findings, for a family view) into a sorted model.
     *
     * @param array<string,mixed>       $manifest
     * @param array<int,array<string,mixed>> $findings
     * @param string|null               $family
     * @return array<string,mixed>
     */
    private function model(array $manifest, array $findings, ?string $family): array
    {
        if ($family !== null && $family === '') {
            throw new InvalidArgumentException('family must be a non-empty string or null');
        }

        $schema = isset($manifest['schema']) ? $manifest['schema'] : null;
        if ($schema !== ManifestBuilder::SCHEMA) {
            throw new InvalidArgumentException('unsupported manifest schema');
        }
        foreach (array('counts', 'bandA', 'corpus', 'enrichers') as $key) {
            if (!isset($manifest[$key]) || !is_array($manifest[$key])) {
                throw new InvalidArgumentException("manifest.$key must be an array");
            }
        }
        $counts = $manifest['counts'];
        foreach (array('band_a', 'corpus_families', 'corpus_keys', 'enrichers') as $key) {
            if (!isset($counts[$key]) || !is_int($counts[$key])) {
                throw new InvalidArgumentException("manifest.counts.$key must be an int");
            }
        }
        if (!isset($manifest['corpus']['families']) || !is_array($manifest['corpus']['families'])
            || !isset($manifest['corpus']['index']) || !is_array($manifest['corpus']['index'])) {
            throw new InvalidArgumentException('manifest.corpus.{families,index} must be arrays');
        }

        $bandA = $manifest['bandA'];
        if (count($bandA) > self::MAX_RECORDS) {
            throw new InvalidArgumentException('too many authored records');
        }

        // Recompute counts for trust; never copy the declared values blindly.
        if ($counts['band_a'] !== count($bandA)) {
            throw new InvalidArgumentException('counts.band_a disagrees with bandA');
        }
        if ($counts['corpus_families'] !== count($manifest['corpus']['families'])) {
            throw new InvalidArgumentException('counts.corpus_families disagrees with corpus.families');
        }
        if ($counts['corpus_keys'] !== count($manifest['corpus']['index'])) {
            throw new InvalidArgumentException('counts.corpus_keys disagrees with corpus.index');
        }
        if ($counts['enrichers'] !== count($manifest['enrichers'])) {
            throw new InvalidArgumentException('counts.enrichers disagrees with enrichers');
        }

        $records = $this->normalizeRecords($bandA);
        $normFindings = $this->normalizeFindings($findings);

        $families = $this->groupFamilies($records, $normFindings);
        ksort($families, SORT_STRING);

        if ($family !== null && !isset($families[$family])) {
            throw new InvalidArgumentException('unknown family: ' . $family);
        }

        return array(
            'counts' => array(
                'schema' => $schema,
                'band_a' => $counts['band_a'],
                'corpus_families' => $counts['corpus_families'],
                'corpus_keys' => $counts['corpus_keys'],
                'enrichers' => $counts['enrichers'],
            ),
            'family_count' => count($families),
            'tier_totals' => $this->tierTotals($records),
            'families' => $families,
            'family' => $family,
        );
    }

    /**
     * @param array<int,mixed> $bandA
     * @return array<int,array<string,mixed>> normalized records, sorted by (id, tier)
     */
    private function normalizeRecords(array $bandA): array
    {
        $records = array();
        $seenIds = array();
        foreach ($bandA as $raw) {
            if (!is_array($raw)) {
                throw new InvalidArgumentException('bandA record must be an array');
            }
            $id = $this->scalarString($raw, 'id', true);
            $tier = $this->scalarString($raw, 'tier', true);
            $familyName = $this->scalarString($raw, 'family', true);
            $severity = $this->scalarString($raw, 'severity', false);
            if (isset($seenIds[$id])) {
                throw new InvalidArgumentException('duplicate authored id: ' . $id);
            }
            $seenIds[$id] = true;
            if (!array_key_exists('unanchored', $raw) || !is_bool($raw['unanchored'])) {
                throw new InvalidArgumentException("record $id: unanchored must be a bool");
            }
            if (!isset($raw['owned_routes']) || !is_array($raw['owned_routes'])
                || !isset($raw['outbound_links']) || !is_array($raw['outbound_links'])) {
                throw new InvalidArgumentException("record $id: owned_routes/outbound_links must be arrays");
            }
            if (count($raw['owned_routes']) > self::MAX_ROUTES_PER_RECORD) {
                throw new InvalidArgumentException("record $id: too many owned routes");
            }
            if (count($raw['outbound_links']) > self::MAX_LINKS_PER_RECORD) {
                throw new InvalidArgumentException("record $id: too many outbound links");
            }

            $records[] = array(
                'id' => $id,
                'tier' => $tier,
                'family' => $familyName,
                'severity' => $this->canonicalSeverity($severity),
                'unanchored' => $raw['unanchored'],
                'routes' => $this->normalizeRoutes($id, $raw['owned_routes']),
                'links' => $this->normalizeLinks($id, $raw['outbound_links']),
            );
        }

        usort($records, function (array $a, array $b) {
            $c = strcmp($a['id'], $b['id']);

            return $c !== 0 ? $c : strcmp($a['tier'], $b['tier']);
        });

        return $records;
    }

    /**
     * @param array<int,mixed> $routes
     * @return array<int,array<string,string>> unique routes sorted by (method, path, via)
     */
    private function normalizeRoutes(string $id, array $routes): array
    {
        $out = array();
        foreach ($routes as $route) {
            if (!is_array($route)) {
                throw new InvalidArgumentException("record $id: route must be an array");
            }
            $out[] = array(
                'method' => $this->scalarString($route, 'method', true),
                'path' => $this->scalarString($route, 'path', true),
                'via' => $this->scalarString($route, 'via', true),
            );
        }
        $out = $this->dedupeSorted($out, function (array $r) {
            return $r['method'] . "\0" . $r['path'] . "\0" . $r['via'];
        });

        return $out;
    }

    /**
     * @param array<int,mixed> $links
     * @return array<int,array<string,mixed>> unique links sorted by (source, path, relative)
     */
    private function normalizeLinks(string $id, array $links): array
    {
        $out = array();
        foreach ($links as $link) {
            if (!is_array($link)) {
                throw new InvalidArgumentException("record $id: link must be an array");
            }
            if (!array_key_exists('relative', $link) || !is_bool($link['relative'])) {
                throw new InvalidArgumentException("record $id: link.relative must be a bool");
            }
            $out[] = array(
                'path' => $this->scalarString($link, 'path', false),
                'source' => $this->scalarString($link, 'source', false),
                'relative' => $link['relative'],
            );
        }
        $out = $this->dedupeSorted($out, function (array $l) {
            return $l['source'] . "\0" . $l['path'] . "\0" . ($l['relative'] ? '1' : '0');
        });

        return $out;
    }

    /**
     * @param array<int,mixed> $findings
     * @return array<int,array<string,mixed>> normalized findings sorted by fixed key
     */
    private function normalizeFindings(array $findings): array
    {
        if (count($findings) > self::MAX_FINDINGS) {
            throw new InvalidArgumentException('too many findings');
        }
        $out = array();
        foreach ($findings as $f) {
            if (!is_array($f)) {
                throw new InvalidArgumentException('finding must be an array');
            }
            $severity = $this->scalarString($f, 'severity', false);
            if (!isset(self::$findingRank[$severity])) {
                // A finding severity outside the known set is a config/API mismatch, not a decoy fact.
                throw new InvalidArgumentException('unknown finding severity: ' . $severity);
            }
            $out[] = array(
                'check' => $this->scalarString($f, 'check', false),
                'severity' => $severity,
                'a' => $this->scalarString($f, 'a', false),
                'b' => $this->scalarString($f, 'b', false),
                'path' => $this->scalarString($f, 'path', false),
                'message' => $this->scalarString($f, 'message', false),
                'accepted_reason' => isset($f['accepted_reason']) ? $this->scalarString($f, 'accepted_reason', false) : '',
            );
        }
        $out = $this->dedupeSorted($out, array($this, 'findingSortKey'));

        return $out;
    }

    /**
     * Sort key placing findings in fail > warn > accepted > info order, then by every displayed
     * field so distinct findings never collapse.
     *
     * @param array<string,mixed> $f
     */
    private function findingSortKey(array $f): string
    {
        return sprintf('%02d', 99 - self::$findingRank[$f['severity']])
            . "\0" . $f['check'] . "\0" . $f['a'] . "\0" . $f['b']
            . "\0" . $f['path'] . "\0" . $f['message'] . "\0" . $f['accepted_reason'];
    }

    /**
     * Group normalized records by family, attaching matching findings per record.
     *
     * @param array<int,array<string,mixed>> $records
     * @param array<int,array<string,mixed>> $findings
     * @return array<string,array<string,mixed>>
     */
    private function groupFamilies(array $records, array $findings): array
    {
        $families = array();
        foreach ($records as $rec) {
            $fam = $rec['family'];
            if (!isset($families[$fam])) {
                $families[$fam] = array('name' => $fam, 'records' => array());
            }
            $rec['findings'] = $this->findingsFor($rec, $findings);
            $families[$fam]['records'][] = $rec;
        }

        return $families;
    }

    /**
     * Findings that decorate a record: a finding whose `a` or `b` equals the record id. It may also
     * carry a link path — used only in the drill-down to tag matching links.
     *
     * @param array<string,mixed> $rec
     * @param array<int,array<string,mixed>> $findings
     * @return array<int,array<string,mixed>>
     */
    private function findingsFor(array $rec, array $findings): array
    {
        $out = array();
        foreach ($findings as $f) {
            if ($f['a'] === $rec['id'] || $f['b'] === $rec['id']) {
                $out[] = $f;
            }
        }

        return $out;
    }

    /**
     * @param array<int,array<string,mixed>> $records
     * @return array<string,int> tier => count, sorted by tier bytes
     */
    private function tierTotals(array $records): array
    {
        $totals = array();
        foreach ($records as $rec) {
            $tier = $rec['tier'];
            $totals[$tier] = isset($totals[$tier]) ? $totals[$tier] + 1 : 1;
        }
        ksort($totals, SORT_STRING);

        return $totals;
    }

    // ---- Overview rendering -------------------------------------------------

    /**
     * @param array<string,mixed> $model
     */
    private function overviewMarkdown(array $model): string
    {
        $c = $model['counts'];
        $out = array();
        $out[] = '# Decoy map';
        $out[] = '';
        $out[] = '> GENERATED by `bin/funnypot map` from `resources/compiled/funnypot-manifest.php` — DO NOT EDIT.';
        $out[] = '> The manifest is the sole inventory authority; friendly names, categories and behavior';
        $out[] = '> prose live in the README taxonomy, not here.';
        $out[] = '';
        $out[] = 'Manifest schema ' . $c['schema'] . '. Authored records: ' . $c['band_a']
            . ' across ' . $model['family_count'] . ' families. Corpus: ' . $c['corpus_families']
            . ' families / ' . $c['corpus_keys'] . ' route keys (summarized, not enumerated). Enrichers: '
            . $c['enrichers'] . '.';
        $out[] = '';
        $out[] = '```mermaid';
        $out[] = $this->overviewMermaid($model);
        $out[] = '```';
        $out[] = '';
        $out[] = '| Family | Authored records | Tier mix | Owned routes | Outbound links | Max severity | Integrity |';
        $out[] = '|---|---|---|---|---|---|---|';
        foreach ($model['families'] as $fam) {
            $agg = $this->familyAggregate($fam);
            $out[] = '| ' . $this->md($fam['name'])
                . ' | ' . $agg['records']
                . ' | ' . $this->md($agg['tier_mix'])
                . ' | ' . $agg['routes']
                . ' | ' . $agg['links']
                . ' | ' . $this->md($agg['max_severity'])
                . ' | ' . $agg['integrity'] . ' |';
        }
        $out[] = '| _corpus (nuclei-inversion)_ | ' . $c['corpus_families'] . ' families / '
            . $c['corpus_keys'] . ' keys | &mdash; | &mdash; | &mdash; | &mdash; | &mdash; |';
        $out[] = '| _content enrichers (not route claimers)_ | ' . $c['enrichers']
            . ' | &mdash; | &mdash; | &mdash; | &mdash; | &mdash; |';
        $out[] = '';
        $out[] = 'Per-family detail: `bin/funnypot map --family=NAME --format=md` '
            . '(or `--format=mermaid` for the raw flowchart).';

        return implode("\n", $out) . "\n";
    }

    /**
     * @param array<string,mixed> $model
     */
    private function overviewMermaid(array $model): string
    {
        $c = $model['counts'];
        $lines = array();
        $lines[] = 'mindmap';
        $lines[] = '  root((funnypot decoys))';
        $i = 0;
        foreach ($model['families'] as $fam) {
            $i++;
            $agg = $this->familyAggregate($fam);
            $label = $fam['name'] . ': ' . $agg['records'];
            $lines[] = '    fam' . $this->ordinal($i) . '["' . $this->mermaid($label) . '"]';
        }
        $lines[] = '    corpus["' . $this->mermaid('corpus: ' . $c['corpus_families']
            . ' families / ' . $c['corpus_keys'] . ' keys') . '"]';
        $lines[] = '    enrichers["' . $this->mermaid('content enrichers (not route claimers): '
            . $c['enrichers']) . '"]';

        return implode("\n", $lines);
    }

    // ---- Family drill-down rendering ---------------------------------------

    /**
     * @param array<string,mixed> $model
     */
    private function familyMarkdown(array $model): string
    {
        $fam = $model['families'][$model['family']];
        $out = array();
        $out[] = '# Decoy family: ' . $this->md($fam['name']);
        $out[] = '';
        $out[] = '> GENERATED by `bin/funnypot map --family=' . $this->md($fam['name'])
            . '` from `resources/compiled/funnypot-manifest.php` — DO NOT EDIT.';
        $out[] = '';
        $out[] = 'Manifest schema ' . $model['counts']['schema'] . '. '
            . count($fam['records']) . ' authored record(s) in this family. Owned routes and outbound'
            . ' links are recorded per decoy; schema 1 carries no route&#8209;to&#8209;link association,'
            . ' so they are shown as independent branches.';
        $out[] = '';
        $out[] = '```mermaid';
        $out[] = $this->familyMermaid($model);
        $out[] = '```';

        $findingRows = array();
        foreach ($fam['records'] as $rec) {
            $out[] = '';
            $out[] = '## ' . $this->md($rec['id']);
            $out[] = '';
            $out[] = '- Tier: `' . $this->md($rec['tier']) . '`';
            $out[] = '- Max severity: `' . $this->md($rec['severity']) . '`';
            $out[] = '- ' . ($rec['unanchored'] ? 'Unanchored (no route claim in manifest)' : 'Anchored');

            if ($rec['routes']) {
                $out[] = '- Owned routes:';
                foreach ($rec['routes'] as $r) {
                    $out[] = '  - `' . $this->md($r['method']) . ' ' . $this->md($r['path'])
                        . '` via `' . $this->md($r['via']) . '`';
                }
            } elseif ($rec['unanchored']) {
                $out[] = '- Owned routes: unanchored; no route claim in manifest';
            } else {
                $out[] = '- Owned routes: none recorded';
            }

            if ($rec['links']) {
                $out[] = '- Outbound links:';
                foreach ($rec['links'] as $l) {
                    $out[] = '  - `' . $this->md($l['path']) . '` (' . $this->md($l['source'])
                        . ', ' . ($l['relative'] ? 'relative' : 'absolute') . ')';
                }
            } else {
                $out[] = '- Outbound links: no recorded outbound links';
            }

            foreach ($rec['findings'] as $f) {
                $findingRows[] = $f;
            }
        }

        if ($findingRows) {
            $findingRows = $this->dedupeSorted($findingRows, array($this, 'findingSortKey'));
            $out[] = '';
            $out[] = '## Route-integrity findings';
            $out[] = '';
            $out[] = '| Severity | Check | A | B | Path | Detail |';
            $out[] = '|---|---|---|---|---|---|';
            foreach ($findingRows as $f) {
                $detail = $f['message'];
                if ($f['accepted_reason'] !== '') {
                    $detail .= ' (accepted: ' . $f['accepted_reason'] . ')';
                }
                $out[] = '| ' . $this->md($f['severity'])
                    . ' | ' . $this->md($f['check'])
                    . ' | ' . $this->md($f['a'])
                    . ' | ' . $this->md($f['b'])
                    . ' | ' . $this->md($f['path'])
                    . ' | ' . $this->md($detail) . ' |';
            }
        }

        return implode("\n", $out) . "\n";
    }

    /**
     * @param array<string,mixed> $model
     */
    private function familyMermaid(array $model): string
    {
        $fam = $model['families'][$model['family']];
        $lines = array();
        $lines[] = 'flowchart TD';
        $lines[] = '  fam0001["' . $this->mermaid($fam['name']) . '"]';

        $d = 0;
        foreach ($fam['records'] as $rec) {
            $d++;
            $decId = 'dec' . $this->ordinal($d);
            $lines[] = '  ' . $decId . '["' . $this->mermaid($rec['id'] . ' / ' . $rec['tier']) . '"]';
            $lines[] = '  fam0001 --> ' . $decId;

            $routesId = $decId . 'r';
            $linksId = $decId . 'l';
            $lines[] = '  ' . $routesId . '["' . $this->mermaid('owned routes') . '"]';
            $lines[] = '  ' . $linksId . '["' . $this->mermaid('outbound links') . '"]';
            $lines[] = '  ' . $decId . ' --> ' . $routesId;
            $lines[] = '  ' . $decId . ' --> ' . $linksId;

            if ($rec['routes']) {
                $ri = 0;
                foreach ($rec['routes'] as $r) {
                    $ri++;
                    $nid = $decId . 'route' . $this->ordinal($ri);
                    $label = $r['method'] . ' ' . $r['path'] . ' via ' . $r['via'];
                    $lines[] = '  ' . $nid . '["' . $this->mermaid($label) . '"]';
                    $lines[] = '  ' . $routesId . ' --> ' . $nid;
                }
            } else {
                $nid = $decId . 'route0000';
                $text = $rec['unanchored'] ? 'unanchored; no route claim in manifest' : 'none recorded';
                $lines[] = '  ' . $nid . '["' . $this->mermaid($text) . '"]';
                $lines[] = '  ' . $routesId . ' --> ' . $nid;
            }

            if ($rec['links']) {
                $li = 0;
                foreach ($rec['links'] as $l) {
                    $li++;
                    $nid = $decId . 'link' . $this->ordinal($li);
                    $label = $l['path'] . ' ' . $l['source'] . ' ' . ($l['relative'] ? 'relative' : 'absolute');
                    $lines[] = '  ' . $nid . '["' . $this->mermaid($label) . '"]';
                    $lines[] = '  ' . $linksId . ' --> ' . $nid;
                }
            } else {
                $nid = $decId . 'link0000';
                $lines[] = '  ' . $nid . '["' . $this->mermaid('no recorded outbound links') . '"]';
                $lines[] = '  ' . $linksId . ' --> ' . $nid;
            }
        }

        return implode("\n", $lines);
    }

    /**
     * @param array<string,mixed> $fam
     * @return array<string,mixed>
     */
    private function familyAggregate(array $fam): array
    {
        $tierCounts = array();
        $routes = 0;
        $links = 0;
        $maxRank = -1;
        $maxSeverity = 'unknown';
        $findingRanks = array();
        foreach ($fam['records'] as $rec) {
            $tierCounts[$rec['tier']] = isset($tierCounts[$rec['tier']]) ? $tierCounts[$rec['tier']] + 1 : 1;
            $routes += count($rec['routes']);
            $links += count($rec['links']);
            $rank = $this->severityRank($rec['severity']);
            if ($rank > $maxRank) {
                $maxRank = $rank;
                $maxSeverity = $rec['severity'];
            }
            foreach ($rec['findings'] as $f) {
                $findingRanks[$f['severity']] = true;
            }
        }
        ksort($tierCounts, SORT_STRING);
        $mix = array();
        foreach ($tierCounts as $tier => $n) {
            $mix[] = $tier . ':' . $n;
        }

        $integrity = '&mdash;';
        if ($findingRanks) {
            $order = array('fail', 'warn', 'accepted', 'info');
            $parts = array();
            foreach ($order as $sev) {
                if (isset($findingRanks[$sev])) {
                    $parts[] = $sev;
                }
            }
            $integrity = implode(', ', $parts);
        }

        return array(
            'records' => count($fam['records']),
            'tier_mix' => implode(' ', $mix),
            'routes' => $routes,
            'links' => $links,
            'max_severity' => $maxSeverity,
            'integrity' => $integrity,
        );
    }

    private function severityRank(string $severity): int
    {
        return isset(self::$severityRank[$severity]) ? self::$severityRank[$severity] : 0;
    }

    /**
     * Empty severity is `unknown`; a known value is kept; any other non-empty value is displayed as
     * `unknown(<value>)` and ranks below the known values.
     */
    private function canonicalSeverity(string $severity): string
    {
        if ($severity === '') {
            return 'unknown';
        }
        if (isset(self::$severityRank[$severity])) {
            return $severity;
        }

        return 'unknown(' . $severity . ')';
    }

    // ---- Validation + escaping helpers -------------------------------------

    /**
     * Fetch a string field, validating UTF-8, NUL-freeness and byte ceiling. An unrecognized
     * non-empty severity is displayed as `unknown(<value>)`; that mapping happens at the caller.
     *
     * @param array<string,mixed> $arr
     */
    private function scalarString(array $arr, string $key, bool $required): string
    {
        if (!array_key_exists($key, $arr)) {
            if ($required) {
                throw new InvalidArgumentException("missing required field: $key");
            }

            return '';
        }
        $value = $arr[$key];
        if ($value === null && !$required) {
            return '';
        }
        if (!is_string($value)) {
            throw new InvalidArgumentException("field $key must be a string");
        }
        if ($required && $value === '') {
            throw new InvalidArgumentException("field $key must be non-empty");
        }
        if (strlen($value) > self::MAX_SCALAR_BYTES) {
            throw new InvalidArgumentException("field $key exceeds byte ceiling");
        }
        if (strpos($value, "\0") !== false) {
            throw new InvalidArgumentException("field $key contains NUL");
        }
        if ($value !== '' && !$this->isValidUtf8($value)) {
            throw new InvalidArgumentException("field $key is not valid UTF-8");
        }

        return $value;
    }

    private function isValidUtf8(string $s): bool
    {
        return preg_match('//u', $s) === 1;
    }

    /**
     * Collapse byte-identical entries by comparison key, then sort by that key; a stable ordinal
     * appended to the key keeps distinct-but-equal-prefix items deterministic.
     *
     * @param array<int,array<string,mixed>> $items
     * @param callable                       $keyFn item => comparison key
     * @return array<int,array<string,mixed>>
     */
    private function dedupeSorted(array $items, callable $keyFn): array
    {
        $byKey = array();
        foreach ($items as $item) {
            $byKey[$keyFn($item)] = $item;
        }
        uksort($byKey, 'strcmp');

        return array_values($byKey);
    }

    private function assertOneMarker(string $haystack, string $marker): void
    {
        $count = substr_count($haystack, $marker);
        if ($count === 0) {
            throw new InvalidArgumentException("missing marker: $marker");
        }
        if ($count > 1) {
            throw new InvalidArgumentException("duplicate marker: $marker");
        }
    }

    private function ordinal(int $n): string
    {
        return str_pad((string) $n, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Mermaid label encoder. Labels live inside one fixed `"..."` node position. Keep the small
     * printable ASCII whitelist and valid UTF-8 bytes; every other ASCII byte becomes Mermaid's
     * decimal entity `#NN;`. Because `#`, quotes, brackets, braces, parens, angle brackets, pipe,
     * backslash, backtick, percent, semicolon, CR/LF and controls are never emitted, input cannot
     * close the node, add an edge/directive or escape a fence.
     */
    private function mermaid(string $s): string
    {
        return $this->encode($s, '#');
    }

    /**
     * Markdown cell/text encoder. Same printable whitelist; every other ASCII byte becomes the
     * decimal HTML entity `&#NN;`. Already-encoded input is not decoded — `&#124;` re-encodes as
     * data, never a pipe.
     */
    private function md(string $s): string
    {
        return $this->encode($s, '&#');
    }

    /**
     * Shared encoder: keep whitelisted printable ASCII and UTF-8 multibyte bytes; entity-encode
     * every other ASCII code point with the given prefix (`#NN;` for Mermaid, `&#NN;` for Markdown).
     */
    private function encode(string $s, string $prefix): string
    {
        static $whitelist = null;
        if ($whitelist === null) {
            $whitelist = array();
            $safe = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 _./:@+-';
            $len = strlen($safe);
            for ($i = 0; $i < $len; $i++) {
                $whitelist[$safe[$i]] = true;
            }
        }

        $out = '';
        $len = strlen($s);
        for ($i = 0; $i < $len; $i++) {
            $ch = $s[$i];
            $code = ord($ch);
            if ($code >= 0x80) {
                // Multibyte UTF-8 continuation/lead byte; string was UTF-8 validated upstream.
                $out .= $ch;
            } elseif (isset($whitelist[$ch])) {
                $out .= $ch;
            } else {
                $out .= $prefix . $code . ';';
            }
        }

        return $out;
    }
}
