<?php

declare(strict_types=1);

namespace Funnypot\Core\Compiler;

use RuntimeException;

/**
 * Writes the compiled index and its sidecars to disk. The index is a literal
 * `return [...]` file frozen by opcache at runtime; manifest.json and skipped.json are
 * the coverage audit.
 */
final class ArtifactWriter
{
    /** @var PhpArrayExporter */
    private $exporter;

    public function __construct()
    {
        $this->exporter = new PhpArrayExporter();
    }

    /**
     * @param array{index:array,manifest:array,skipped:array,stats:array} $result
     * @param array<string,string> $provenance sidecar-only compile record: `built_at`,
     *                                         `core_commit`, `php_version` (each optional)
     * @return array<string,string> written paths
     */
    public function write(array $result, string $indexPath, array $provenance = []): array
    {
        $dir = dirname($indexPath);
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new RuntimeException("Cannot create output dir: {$dir}");
        }

        $php = $this->render($result['index']);
        $this->atomicWrite($indexPath, $php);

        $sha = hash('sha256', $php);
        $manifest = $result['manifest'];
        // Sidecar-only compile record (none of it reaches the index, which stays byte-reproducible):
        // built_at is the caller's reproducible stamp when given (SOURCE_DATE_EPOCH / upstream commit
        // date, see bin/funnypot resolveUpstream) and wall-clock otherwise; core_commit + php_version
        // say which compiler produced the corpus half. Field ORDER is a contract: merge-routes
        // re-emits the sidecar in exactly this order when it refreshes the fingerprint.
        $manifest['built_at'] = isset($provenance['built_at']) ? (string) $provenance['built_at'] : gmdate('c');
        $manifest['core_commit'] = (string) ($provenance['core_commit'] ?? 'unknown');
        $manifest['php_version'] = (string) ($provenance['php_version'] ?? PHP_VERSION);
        $manifest['sha256'] = $sha;
        $manifest['skipped_count'] = count($result['skipped']);
        $manifest['artifact_bytes'] = strlen($php);

        $manifestPath = $dir . '/manifest.json';
        $skippedPath = $dir . '/skipped.json';
        $this->atomicWrite($manifestPath, $this->json($manifest));
        $this->atomicWrite($skippedPath, $this->json($result['skipped']));

        return [
            'index' => $indexPath,
            'manifest' => $manifestPath,
            'skipped' => $skippedPath,
            'sha256' => $sha,
        ];
    }

    private function render(array $index): string
    {
        $body = $this->exporter->export($index, 0);

        return <<<PHP
<?php

/**
 * COMPILED TEMPLATE INDEX — schema 1. GENERATED by bin/funnypot — DO NOT EDIT.
 *
 * A 100%-literal array (no objects/closures/::class) loadable by PhpArrayStore and
 * frozen by opcache into shared memory at runtime.
 *
 * Derived from projectdiscovery/nuclei-templates (MIT, (c) 2025 ProjectDiscovery,
 * Inc.). See resources/UPSTREAM-LICENSE.md.
 */

declare(strict_types=1);

return {$body};

PHP;
    }

    private function json($data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . "\n";
    }

    private function atomicWrite(string $path, string $contents): void
    {
        $tmp = $path . '.tmp.' . getmypid();
        if (@file_put_contents($tmp, $contents) === false) {
            throw new RuntimeException("Write failed: {$tmp}");
        }
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            throw new RuntimeException("Rename failed: {$path}");
        }
    }
}
