<?php

declare(strict_types=1);

namespace Funnypot\Core\Compiler;

use RuntimeException;

/**
 * The one atomic writer every compile-* step emits its `return [...]` artifact through.
 *
 * Two jobs, both previously duplicated as bare `file_put_contents` at six sites in bin/funnypot:
 *
 *   1. Standard header — `<?php` + `declare(strict_types=1)` + the `GENERATED by … — DO NOT EDIT.`
 *      line + an optional `Provenance: source-tree sha256=…` line — so the provenance stamp can
 *      never be forgotten per-step (it lives in one place).
 *   2. tmp-file + atomic rename — a crash mid-write can no longer leave a torn half-artifact that
 *      the runtime would `require`.
 *
 * The body is `var_export`, matching every existing compile artifact byte-for-byte (so this is a
 * pure lift; the only new bytes are the optional provenance line). The index itself is written by
 * ArtifactWriter (PhpArrayExporter) / merge-routes, not here.
 */
final class GeneratedPhp
{
    /**
     * @param string      $generatorLine e.g. "`funnypot compile-emulators`" — filled into the GENERATED header
     * @param mixed       $data          the pure-literal array to var_export
     * @param string|null $provenance    a 64-hex source-tree sha256, or null to omit the line
     */
    public static function write(string $path, string $generatorLine, $data, ?string $provenance = null): void
    {
        $header = "<?php\n\ndeclare(strict_types=1);\n\n// GENERATED by {$generatorLine} — DO NOT EDIT.\n";
        if ($provenance !== null) {
            $header .= "// Provenance: source-tree sha256={$provenance} schema=1\n";
        }
        $php = $header . "\nreturn " . var_export($data, true) . ";\n";

        self::atomicWrite($path, $php);
    }

    /**
     * tmp-file + rename so a reader never observes a partially written artifact. The tmp name
     * carries the pid so concurrent writers to the same dir don't collide on the temp file.
     */
    public static function atomicWrite(string $path, string $contents): void
    {
        $dir = dirname($path);
        if (!is_dir($dir) && !@mkdir($dir, 0777, true) && !is_dir($dir)) {
            throw new RuntimeException("Cannot create output dir: {$dir}");
        }
        $tmp = $path . '.tmp.' . getmypid();
        if (@file_put_contents($tmp, $contents) === false) {
            throw new RuntimeException("Write failed: {$tmp}");
        }
        if (!@rename($tmp, $path)) {
            @unlink($tmp);
            throw new RuntimeException("Rename failed: {$path}");
        }
    }
}
