<?php

declare(strict_types=1);

namespace Funnypot\Ai;

/**
 * Single source of truth for the advertised AI-model list. Every fake
 * inference-API surface (Ollama /api/tags, /api/ps, /api/show; OpenAI
 * /v1/models; Anthropic /v1/models) reads the same catalog, so a scanner that
 * cross-checks model ids across endpoints always sees one coherent list.
 */
final class ModelCatalog
{
    /** @var array<int,array<string,mixed>> */
    private $models;

    /** @param array<int,array<string,mixed>> $models */
    private function __construct(array $models)
    {
        $this->models = $models;
    }

    /** Loads the real catalog shipped with the package. */
    public static function fromPackage(): self
    {
        return new self(require dirname(__DIR__, 2) . '/resources/ai/model-catalog.php');
    }

    /** @param array<int,array<string,mixed>> $models */
    public static function fromArray(array $models): self
    {
        return new self($models);
    }

    /** @return array<int,array<string,mixed>> */
    public function all(): array
    {
        return $this->models;
    }

    public function has(string $model): bool
    {
        return $this->find($model) !== null;
    }

    /** @return array<string,mixed>|null */
    public function find(string $model): ?array
    {
        foreach ($this->models as $entry) {
            if ($entry['name'] === $model || $entry['openai_id'] === $model) {
                return $entry;
            }
        }

        return null;
    }

    /** @return array<string,mixed> */
    public function ollamaTags(): array
    {
        $models = [];
        foreach ($this->models as $entry) {
            $models[] = $this->tagEntry($entry);
        }

        return ['models' => $models];
    }

    /** @return array<string,mixed> */
    public function ollamaPs(): array
    {
        $loaded = array_slice($this->models, 0, 2);
        $models = [];
        foreach ($loaded as $entry) {
            $models[] = $this->tagEntry($entry) + [
                'expires_at' => self::staticTimestamp(),
                'size_vram' => $entry['size'],
            ];
        }

        return ['models' => $models];
    }

    /** @return array<string,mixed> */
    public function openAiModels(): array
    {
        $data = [];
        foreach ($this->models as $entry) {
            $data[] = [
                'id' => $entry['openai_id'],
                'object' => 'model',
                'created' => self::staticUnixTime(),
                'owned_by' => $entry['owned_by'],
            ];
        }

        return ['object' => 'list', 'data' => $data];
    }

    /** @return array<string,mixed> */
    public function anthropicModels(): array
    {
        $data = [];
        foreach ($this->models as $entry) {
            $data[] = [
                'id' => $entry['openai_id'],
                'type' => 'model',
                'display_name' => $entry['display_name'],
                'created_at' => self::staticTimestamp(),
            ];
        }

        return [
            'data' => $data,
            'first_id' => $data[0]['id'] ?? null,
            'has_more' => false,
            'last_id' => $data[count($data) - 1]['id'] ?? null,
        ];
    }

    /** @return array<string,mixed>|null */
    public function ollamaShow(string $model): ?array
    {
        $entry = $this->find($model);
        if ($entry === null) {
            return null;
        }

        $details = $this->detailsBlock($entry);

        return [
            'modelfile' => "# Modelfile generated by \"ollama show\"\n"
                . "# To build a new Modelfile based on this one, replace the FROM line with:\n"
                . "# FROM {$entry['name']}\n\n"
                . "FROM {$entry['name']}\n"
                . "TEMPLATE \"\"\"{{ .Prompt }}\"\"\"\n"
                . "PARAMETER stop \"<|end|>\"\n",
            'parameters' => "num_ctx                       {$entry['context_length']}\n"
                . "stop                           \"<|end|>\"\n"
                . "temperature                    0.7\n",
            'template' => '{{ .Prompt }}',
            'details' => $details,
            'model_info' => [
                'general.architecture' => $entry['family'],
                'general.parameter_count' => self::parameterCount((string) $entry['parameter_size']),
                'general.quantization_version' => 2,
                'general.file_type' => $entry['quantization_level'],
                $entry['family'] . '.context_length' => $entry['context_length'],
            ],
            'capabilities' => ['completion'],
        ];
    }

    /** @param array<string,mixed> $entry */
    private function tagEntry(array $entry): array
    {
        return [
            'name' => $entry['name'],
            'model' => $entry['name'],
            'modified_at' => self::staticTimestamp(),
            'size' => $entry['size'],
            'digest' => $entry['digest'],
            'details' => $this->detailsBlock($entry),
        ];
    }

    /** @param array<string,mixed> $entry */
    private function detailsBlock(array $entry): array
    {
        return [
            'parent_model' => '',
            'format' => 'gguf',
            'family' => $entry['family'],
            'families' => $entry['families'],
            'parameter_size' => $entry['parameter_size'],
            'quantization_level' => $entry['quantization_level'],
        ];
    }

    /** A fixed size scale (T/B/M) to a rough parameter count, for the /api/show model_info block. */
    private static function parameterCount(string $parameterSize): int
    {
        $unit = strtoupper(substr($parameterSize, -1));
        $value = (float) substr($parameterSize, 0, -1);
        $scale = ['T' => 1e12, 'B' => 1e9, 'M' => 1e6][$unit] ?? 1;

        return (int) ($value * $scale);
    }

    /** One fixed RFC3339 instant for every catalog-derived timestamp — the catalog is static data. */
    private static function staticTimestamp(): string
    {
        return '2026-08-01T00:00:00Z';
    }

    private static function staticUnixTime(): int
    {
        return 1769904000; // 2026-02-01T00:00:00Z
    }
}
