<?php

declare(strict_types=1);

namespace Funnypot\Core\Tests\Crs;

use Funnypot\Core\Compiler\Crs\CrsArchetypes;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Yaml\Yaml;

/**
 * FP-0279 — the permanent CRS-archetype sync lint. The committed templates/attack-crs/*.yaml are
 * GENERATED by `funnypot compile-crs`, which needs a CoreRuleSet checkout the coder does not have —
 * so they are regenerated by hand from the archetype recipe. Their `response`/`expect` are a pure
 * function of CrsArchetypes::for($class), so this test pins them: editing a hand-authored source
 * (e.g. 50-sqli.yaml's body, or CrsArchetypes::inline('xss')) WITHOUT re-syncing its CRS twin fails
 * here — the mechanism that keeps 950 ⇔ 50-sqli and 951 ⇔ inline('xss') coherent forever, so a
 * later CRS refresh re-derives the SAME bodies and produces no drift.
 *
 * This assertion FAILS against a tree where a CRS twin's body was changed out of step with its
 * archetype (or, pre-FP-0279, would have failed had the archetype carried directives the twin lacked).
 * Fixtures: the committed templates/attack-crs/*.yaml + their hand-authored sources.
 */
final class CrsArchetypeSyncTest extends TestCase
{
    private const ROOT = __DIR__ . '/../..';

    public function test_every_committed_crs_template_matches_its_archetype(): void
    {
        $archetypes = new CrsArchetypes(self::ROOT);
        $files = glob(self::ROOT . '/templates/attack-crs/*.yaml') ?: [];
        self::assertNotEmpty($files, 'there must be committed CRS templates to check');

        $checked = 0;
        foreach ($files as $file) {
            $doc = Yaml::parseFile($file);
            $id = (string) ($doc['id'] ?? '');
            self::assertStringStartsWith('attack-crs-', $id, "{$file} has a CRS id");
            $class = substr($id, strlen('attack-crs-'));
            self::assertTrue(CrsArchetypes::isKnown($class), "{$file}: '{$class}' is a known archetype class");

            $arch = $archetypes->for($class);
            $response = [
                'headers' => array_map('strval', (array) ($doc['response']['headers'] ?? [])),
                'body' => (string) ($doc['response']['body'] ?? ''),
            ];
            self::assertSame($arch['response'], $response, "{$file}: response is out of sync with the {$class} archetype — re-run the regen recipe");
            self::assertSame($arch['expect'], array_map('strval', (array) ($doc['expect'] ?? [])), "{$file}: expect is out of sync with the {$class} archetype");
            $checked++;
        }
        self::assertGreaterThanOrEqual(4, $checked, 'all four CRS classes are checked');
    }
}
