<?php

declare(strict_types=1);

namespace Funnypot\Core\Response;

use Funnypot\Core\Template\DirectiveRenderer;

/**
 * One data-driven endpoint emulator, replacing all the hand-coded Response\Emulator
 * classes. It looks up the matching route template for a served bundle and renders its
 * authored body/headers through the bounded DirectiveRenderer, deriving realistic and
 * taunt styles from a single authored body.
 *
 * Correctness is guaranteed DOWNSTREAM, not by the template: ResponseSynthesizer re-runs
 * BundleValidator + typed-header + regex/size checks on this output and falls back to
 * minimal synthesis on any mismatch — so a badly authored body degrades to minimal, it
 * can never break a matcher. appendMissingTokens() is the belt-and-braces: every required
 * body word is guaranteed present regardless of what the author wrote.
 */
final class RouteTemplateEmulator extends AbstractEmulator
{
    /**
     * Ceiling on a generated binary body — Config's default maxBodyBytes. Enforced here so a generator
     * can never hand the synthesizer an amplifier; the operator's configured cap still applies
     * downstream and may be lower. Inclusive: exactly this many bytes serves.
     */
    public const MAX_GENERATED_BODY_BYTES = 65536;

    /** @var RouteTemplateSet */
    private $set;

    /** @var DirectiveRenderer */
    private $renderer;

    /** @var bool opt-in LLM prompt-injection seeding gate (FP-0239); false ⇒ no injection block. */
    private $promptInjectionSeeding;

    /** @var array<string,string> operator canary map (e.g. ['beacon' => '<self-beacon url>']); empty ⇒ no URL. */
    private $beaconCanary;

    /** @var BinaryBodyGeneratorRegistry the closed generators a `binary_generator` rule may resolve to */
    private $generators;

    /**
     * @param array<string,string> $beaconCanary
     * @param BinaryBodyGeneratorRegistry|null $generators null ⇒ the built-in registry, so every
     *                              construction site (including the CI render gates) serves generated
     *                              bodies; tests inject a registry to pin the decline paths.
     */
    public function __construct(
        RouteTemplateSet $set,
        ?DirectiveRenderer $renderer = null,
        bool $promptInjectionSeeding = false,
        array $beaconCanary = [],
        ?BinaryBodyGeneratorRegistry $generators = null
    ) {
        $this->set = $set;
        $this->renderer = $renderer ?? new DirectiveRenderer();
        $this->promptInjectionSeeding = $promptInjectionSeeding;
        $this->beaconCanary = $beaconCanary;
        $this->generators = $generators ?? BinaryBodyGeneratorRegistry::default();
    }

    public function supports(array $bundle, ?string $routeKey = null): bool
    {
        return $this->set->findRule($bundle, $routeKey) !== null;
    }

    public function render(array $bundle, string $style, int $seed, ?string $routeKey = null): ?EmulatedContent
    {
        $rule = $this->set->findRule($bundle, $routeKey);
        if ($rule === null) {
            return null;
        }

        // Binary rule (FP-0230): the bytes are served VERBATIM — generated by a closed built-in
        // writer when the rule names a `binary_generator`, else base64-decoded from the body at rest.
        // No DirectiveRenderer over the bytes, no taunt, no injection, no appendMissingTokens (a bin
        // bundle carries no body words). Headers are still authored text (Content-Type: image/x-icon
        // | application/octet-stream, no charset) and render normally. The generator branch comes
        // FIRST: a generator rule's compiled body is a non-base64 sentinel that only an older runtime
        // ever decodes (and declines on). A corrupt asset or a declined generation returns null (the
        // app serves its 404).
        if (!empty($rule['bin'])) {
            if (isset($rule['binary_generator'])) {
                $bytes = $this->generateBinary((string) $rule['binary_generator'], $seed);
            } else {
                $decoded = base64_decode((string) ($rule['body'] ?? ''), true);
                $bytes = $decoded === false ? null : $decoded;
            }
            if ($bytes === null) {
                return null;
            }
            $binHeaders = [];
            foreach ((array) ($rule['headers'] ?? []) as $name => $value) {
                $binHeaders[(string) $name] = $this->renderer->render((string) $value, [], $seed);
            }

            return new EmulatedContent($bytes, $binHeaders);
        }

        // Routes have no attacker payload, so captures are empty (seed-only directives). The 4th arg
        // is the operator canary map — empty on the default path (byte-identical to pre-FP-0239), and
        // carries the self-beacon URL only when prompt-injection seeding is configured on.
        //
        // FP-0244 note: the canary map is passed to this WHOLE-BODY render, not only to the injection
        // block below. No shipped template body contains {{canary.beacon}} today; if a future compiled
        // template did, the URL would resolve here, outside the injection block. That is harmless — it
        // is the operator's own signed URL, never attacker input — but the intended single consumer is
        // applyInjection(); a body-level {{canary.beacon}} would be an authoring mistake, not a leak.
        $body = $this->renderer->render((string) ($rule['body'] ?? ''), [], $seed, $this->beaconCanary);

        $headers = [];
        foreach ((array) ($rule['headers'] ?? []) as $name => $value) {
            $headers[(string) $name] = $this->renderer->render((string) $value, [], $seed);
        }

        // A per-request session cookie (fresh random value) — a login/app page that never sets
        // one, or sets a static shared one, is a classic honeypot tell. Only templates that opt
        // in (real stateful apps) get it; static-file exposures never do.
        if (!empty($rule['set_cookie'])) {
            $headers['Set-Cookie'] = $rule['set_cookie'] . '=' . bin2hex(random_bytes(16)) . '; path=/; HttpOnly';
        }

        if ($style === Style::TAUNT && isset($rule['taunt'])) {
            $body = $this->applyTaunt($body, (array) $rule['taunt']);
        }

        // FP-0239: inert prompt-injection + self-beacon seeding, gated ORTHOGONALLY to Style::TAUNT
        // (so a deploy can beacon without the visible troll-face). It reuses the rule's taunt carrier
        // metadata (mode/open/close) but fires under its own opt-in config gate — the flag is consulted
        // HERE, inside the emulator, only because it was threaded Config → Honeypot →
        // EmulatorRegistry::default() → this ctor.
        if ($this->promptInjectionSeeding && isset($rule['taunt'])) {
            $body = $this->applyInjection($body, (array) $rule['taunt'], $seed);
        }

        // Guarantee every required token survives, whatever the author (or the banner) did.
        $body = $this->appendMissingTokens($body, $bundle);

        return new EmulatedContent($body, $headers);
    }

    /**
     * Run one closed-registry generator under the emulator's own guard. An unknown ID, a throw, an
     * empty result or one over the ceiling all decline (null → host 404); nothing is ever truncated,
     * because a partial dump is a worse tell than none. Whatever the generator does, no fault can
     * escape as a 5xx.
     */
    private function generateBinary(string $id, int $seed): ?string
    {
        $generator = $this->generators->find($id);
        if ($generator === null) {
            return null;
        }
        try {
            $bytes = $generator->generate($this->renderer, $seed);
        } catch (\Throwable $e) {
            return null;
        }
        if ($bytes === null || $bytes === '' || strlen($bytes) > self::MAX_GENERATED_BODY_BYTES) {
            return null;
        }

        return $bytes;
    }

    /**
     * Append the "nice try" banner + ASCII troll in the file's own comment syntax, AFTER the body
     * so a human reads the (fabricated) secrets first and only then hits the taunt. Modes:
     *   - line:         each taunt line prefixed with the file's comment token (# , -- , ; )
     *   - block:        the taunt wrapped in one open/close comment ( <!-- … --> )
     *   - inline_field: a JSON string field after the opening brace ( "_comment": "…" ) — JSON has
     *                   no comment syntax, so this is the only way to keep the document parseable.
     *
     * @param array<string,mixed> $taunt
     */
    private function applyTaunt(string $body, array $taunt): string
    {
        $mode = (string) ($taunt['mode'] ?? 'line');
        // Banner text, a blank spacer, then the troll — all raw (no prefix yet).
        $lines = array_merge($this->tauntLines(), [''], $this->tauntArt());

        if ($mode === 'block') {
            $open = (string) ($taunt['open'] ?? '<!--');
            $close = (string) ($taunt['close'] ?? '-->');

            return $body . "\n" . $open . "\n" . implode("\n", $lines) . "\n" . $close . "\n";
        }

        if ($mode === 'inline_field') {
            // JSON: ride the taunt in as a string field so the document still parses. json_encode
            // handles the newlines / backslashes / quotes in the art.
            $key = (string) ($taunt['key'] ?? '_comment');
            $value = (string) json_encode(implode("\n", $lines), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
            $field = '  ' . (string) json_encode($key) . ': ' . $value . ',';
            // FP-0244: inject the field right after the first line (the opening `{`). A single-line JSON
            // body has no newline, so we cannot place the field without a byte-level JSON parse — we
            // SKIP injection and return the body untouched (fail-safe: never risk corrupting valid JSON).
            $nl = strpos($body, "\n");
            if ($nl === false) {
                return $body;
            }

            return substr($body, 0, $nl + 1) . $field . "\n" . substr($body, $nl + 1);
        }

        // line mode: prefix each taunt line with the file's comment token so the doc still parses.
        $open = (string) ($taunt['open'] ?? '#');
        $commented = array_map(
            static function (string $l) use ($open): string {
                return $l === '' ? $open : $open . ' ' . $l;
            },
            $lines
        );

        return $body . "\n" . implode("\n", $commented) . "\n";
    }

    /**
     * Append the INERT prompt-injection block (FP-0239) after the body, in the file's own comment
     * syntax — modelled on applyTaunt(), same three modes (line / block / inline_field). The payload
     * is authored plain-text constants (InjectionPayloads); the ONLY dynamic value is the self-beacon
     * URL, substituted from the server-signed operator canary map via {{canary.beacon}} — and the
     * beacon line is included ONLY when a beacon is configured, so no URL ever appears otherwise.
     *
     * There is no attacker-byte reflection here: the route render passes empty captures and the block
     * is built from constants + a server-derived canary, so an attacker request byte can never land in
     * it. The block stays well under the 2 KB budget; ResponseSynthesizer's size/validator gate is the
     * downstream backstop regardless.
     *
     * @param array<string,mixed> $taunt the rule's taunt carrier metadata (mode/open/close), reused
     */
    private function applyInjection(string $body, array $taunt, int $seed): string
    {
        $lines = InjectionPayloads::MISDIRECTION;
        // Only emit the self-beacon line when an operator beacon URL is actually configured (invariant:
        // rendering with no beacon config emits no URL). {{canary.beacon}} resolves from the map.
        if (($this->beaconCanary['beacon'] ?? '') !== '') {
            $lines[] = $this->renderer->render(InjectionPayloads::BEACON_TEMPLATE, [], $seed, $this->beaconCanary);
        }

        $mode = (string) ($taunt['mode'] ?? 'line');

        if ($mode === 'block') {
            $open = (string) ($taunt['open'] ?? '<!--');
            $close = (string) ($taunt['close'] ?? '-->');

            return $body . "\n" . $open . "\n" . implode("\n", $lines) . "\n" . $close . "\n";
        }

        if ($mode === 'inline_field') {
            // JSON: ride the block in as one string field so the document still parses. A DISTINCT key
            // from the taunt's (fixed '_assessment') so a rule that also emits a taunt _comment (both
            // features on at once) does not produce a duplicate key.
            $value = (string) json_encode(implode(' ', $lines), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
            $field = '  ' . (string) json_encode('_assessment') . ': ' . $value . ',';
            // FP-0244 (same fail-safe as applyTaunt): a single-line JSON body has no newline to anchor
            // the field after the opening `{`, so injection is SKIPPED and the body returned untouched
            // rather than risk corrupting valid JSON.
            $nl = strpos($body, "\n");
            if ($nl === false) {
                return $body;
            }

            return substr($body, 0, $nl + 1) . $field . "\n" . substr($body, $nl + 1);
        }

        // line mode: prefix each line with the file's comment token so the doc still parses.
        $open = (string) ($taunt['open'] ?? '#');
        $commented = array_map(
            static function (string $l) use ($open): string {
                return $l === '' ? $open : $open . ' ' . $l;
            },
            $lines
        );

        return $body . "\n" . implode("\n", $commented) . "\n";
    }
}
