<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-emulators` — DO NOT EDIT.

return array (
  0 => 
  array (
    'id' => 'attack-confluence-26134',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'confluence',
      3 => 'ognl',
      4 => 'cve-2022-26134',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '\\$\\{.*(?:#context|#cmd|@java|@org\\.|getRuntime|ProcessBuilder|Runtime)',
        'dotall' => true,
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html;charset=UTF-8',
        'X-Cmd-Response' => '{{canned.uid}}',
      ),
      'body' => '<!DOCTYPE html><html><head><title>Log In - Confluence</title></head><body><div id="main">Confluence</div></body></html>',
    ),
  ),
  1 => 
  array (
    'id' => 'attack-phpcgi-1823',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'php-cgi',
      2 => 'source-disclosure',
      3 => 'cve-2012-1823',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'query',
        'regex' => '^-[sdw](?:[+ &=]|$)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html',
      ),
      'body' => '<code><span style="color: #000000">
<span style="color: #0000BB">&lt;?php<br /></span>
<span style="color: #007700">$db </span><span style="color: #0000BB">= new mysqli</span><span style="color: #007700">(</span><span style="color: #DD0000">"localhost"</span><span style="color: #007700">, </span><span style="color: #DD0000">"root"</span><span style="color: #007700">, </span><span style="color: #DD0000">"S3cr3tP@ss"</span><span style="color: #007700">);<br /></span>
<span style="color: #0000BB">?&gt;</span>
</span></code>
',
    ),
  ),
  2 => 
  array (
    'id' => 'attack-phpcgi-4577',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'php-cgi',
      2 => 'rce',
      3 => 'cve-2024-4577',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'query',
        'regex' => '%ad(?:d|s)?',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '<!DOCTYPE html><html><head><title>phpinfo()</title></head><body>
<h1 class="p">PHP Version 8.1.10</h1>
<table>
<tr><td class="e">System</td><td class="v">Windows NT WEB01 10.0 build 17763</td></tr>
<tr><td class="e">Server API</td><td class="v">CGI/FastCGI</td></tr>
</table>
<p>This output was generated by phpinfo().</p>
</body></html>
',
    ),
  ),
  3 => 
  array (
    'id' => 'attack-shellshock',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'shellshock',
      3 => 'cve-2014-6271',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'header',
        'contains' => '() {',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.passwd}}',
    ),
  ),
  4 => 
  array (
    'id' => 'attack-struts-ognl',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'struts',
      3 => 'ognl',
      4 => 'cve-2017-5638',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'header:Content-Type',
        'regex' => '%\\{.*(?:#context|#cmd|#_memberAccess|\\(#|multipart/form-data.*[({])',
        'dotall' => true,
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '{{canned.uid}}',
    ),
  ),
  5 => 
  array (
    'id' => 'attack-phpunit-rce',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'phpunit',
      3 => 'cve-2017-9841',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => 'eval-stdin.php',
      ),
      1 => 
      array (
        'in' => 'body',
        'regex' => 'md5\\(["\']?([^)"\']+)["\']?\\)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '{{compute.md5:match.1}}',
    ),
  ),
  6 => 
  array (
    'id' => 'attack-xxe',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'xxe',
      2 => 'file-disclosure',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'body',
        'regex' => '<!ENTITY\\s+\\S+\\s+SYSTEM\\s+["\'\\s]*(?:file:|https?:|php:)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/xml; charset=utf-8',
      ),
      'body' => '{{canned.passwd}}',
    ),
  ),
  7 => 
  array (
    'id' => 'attack-lfi-smbconf',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
      3 => 'smb',
      4 => 'citrix',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => 'smb\\.conf',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '[global]
   workgroup = WORKGROUP
   server string = %h server (Samba)
   security = user
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 1000
[printers]
   comment = All Printers
   path = /var/spool/samba
   browseable = no
',
    ),
  ),
  8 => 
  array (
    'id' => 'attack-lfi-environ',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
      3 => 'proc',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '/proc/self/environ',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.environ}}',
    ),
  ),
  9 => 
  array (
    'id' => 'attack-lfi-shadow',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => 'etc/shadow',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.shadow}}',
    ),
  ),
  10 => 
  array (
    'id' => 'attack-lfi-group',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => 'etc/group',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.group}}',
    ),
  ),
  11 => 
  array (
    'id' => 'attack-lfi-windows',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
      3 => 'windows',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:win\\.ini|boot\\.ini|windows[\\\\/]|system32|c:[\\\\/])',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.winini}}',
    ),
  ),
  12 => 
  array (
    'id' => 'attack-lfi-unix',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'lfi',
      2 => 'traversal',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\\.\\.[\\\\/]|%2e%2e|\\.\\.%2f|\\.\\.%5c|etc/passwd|etc/shadow|/proc/self/environ|wp-config\\.php%00)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.passwd}}',
    ),
  ),
  13 => 
  array (
    'id' => 'attack-cmdi-windows',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'command-injection',
      3 => 'windows',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:[;|&\\n`]|\\$\\(|%0a|%7c|%26)\\s*(?:ipconfig|systeminfo|dir\\b|type\\s)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => 'Windows IP Configuration

Ethernet adapter Ethernet0:
   Connection-specific DNS Suffix  . :
   IPv4 Address. . . . . . . . . . . : 192.0.2.15
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.0.2.1
',
    ),
  ),
  14 => 
  array (
    'id' => 'attack-cmdi-unix',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'command-injection',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:[;|&\\n`]|\\$\\(|%0a|%7c|%26)\\s*(?:id|whoami|uname|cat\\s|ls\\s|pwd|ifconfig)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/plain; charset=utf-8',
      ),
      'body' => '{{canned.uid}}',
    ),
  ),
  15 => 
  array (
    'id' => 'attack-ssti-twig',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'ssti',
      2 => 'twig',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\\{\\{|\\$\\{|\\#\\{|<%=?)\\s*7\\s*\\*\\s*[\'"]7',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '7777777
',
    ),
  ),
  16 => 
  array (
    'id' => 'attack-ssti-numeric',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'ssti',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\\{\\{|\\$\\{|\\#\\{|<%=?)\\s*7\\s*\\*\\s*7',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '49
',
    ),
  ),
  17 => 
  array (
    'id' => 'attack-php-glastopf',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'php-injection',
      3 => 'glastopf',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '\\[php\\][\\s\\S]*?(?:system|passthru|exec|shell_exec|popen)\\s*\\(\\s*[\'"]?(?:id|whoami|uname)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '{{canned.uid}}',
    ),
  ),
  18 => 
  array (
    'id' => 'attack-sqli',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'sqli',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:\'\\s*or\\s*\'?1\'?\\s*=\\s*\'?1|"\\s*or\\s*"?1"?\\s*=|\\bunion\\s+(?:all\\s+)?select\\b|\\bor\\s+1\\s*=\\s*1\\b|information_schema|sleep\\(\\d|\'\\s*--|\\bwaitfor\\s+delay\\b)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\' at line 1
',
    ),
  ),
  19 => 
  array (
    'id' => 'attack-open-redirect',
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'redirect',
      2 => 'open-redirect',
    ),
    'status' => 302,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'query',
        'regex' => '(?:url|redirect|redirect_uri|redirect_url|next|dest|destination|return|returnurl|returnto|goto|target|continue|forward)=((?:https?:)?//[^&]+)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
        'Location' => '{{urldecode:match.1}}',
      ),
      'body' => '<html><head><title>302 Found</title></head><body>Redirecting...</body></html>',
    ),
  ),
  20 => 
  array (
    'id' => 'attack-xss',
    'severity' => 'medium',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'xss',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '<script[^>]*>.*?</script>|<svg[^>]*>.*?</svg>|<img[^>]*\\son\\w+\\s*=[^>]*>|<[a-z][a-z0-9]*[^>]*\\son(?:error|load|mouseover|focus)\\s*=[^>]*>',
        'dotall' => true,
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '<!doctype html><html><head><title>Search</title></head><body>
<h1>Search results</h1><p>No results found for: {{match.0}}</p>
</body></html>
',
    ),
  ),
  21 => 
  array (
    'id' => 'attack-thinkphp-rce',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'thinkphp',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:think.{0,6}app.{0,30}invokefunction|invokefunction.{0,40}call_user_func_array|s=[/\\\\]index[/\\\\].{0,20}phpinfo)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '<!DOCTYPE html><html><head><title>phpinfo()</title></head><body>
<h1 class="p">PHP Version 7.4.33</h1>
<table>
<tr><td class="e">System</td><td class="v">Linux web01 5.15.0 x86_64</td></tr>
<tr><td class="e">Server API</td><td class="v">FPM/FastCGI</td></tr>
</table>
<p>This output was generated by phpinfo().</p>
</body></html>
',
    ),
  ),
  22 => 
  array (
    'id' => 'attack-owncloud-49103',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'owncloud',
      2 => 'phpinfo',
      3 => 'cve-2023-49103',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => 'graphapi/vendor/microsoft/microsoft-graph',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '<!DOCTYPE html><html><head><title>phpinfo()</title></head><body>
<h1 class="p">PHP Version 7.4.3</h1>
<h2>Environment</h2>
<table>
<tr><td class="e">OWNCLOUD_ADMIN_USERNAME</td><td class="v">admin</td></tr>
<tr><td class="e">OWNCLOUD_ADMIN_PASSWORD</td><td class="v">{{fake.ocpw:hex:20}}</td></tr>
<tr><td class="e">OWNCLOUD_DB_PASSWORD</td><td class="v">{{fake.ocdb:hex:24}}</td></tr>
<tr><td class="e">OWNCLOUD_MAIL_SMTP_PASSWORD</td><td class="v">{{fake.ocsmtp:hex:16}}</td></tr>
</table>
<p>This output was generated by phpinfo().</p>
</body></html>
',
    ),
  ),
  23 => 
  array (
    'id' => 'attack-f5-1388',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'f5',
      3 => 'big-ip',
      4 => 'cve-2022-1388',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => '/mgmt/tm/util/bash',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/json; charset=UTF-8',
      ),
      'body' => '{"kind":"tm:util:bash:runstate","command":"run","utilCmdArgs":"-c id","commandResult":"uid=0(root) gid=0(root) groups=0(root)\\n"}
',
    ),
  ),
  24 => 
  array (
    'id' => 'attack-geoserver-36401',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'rce',
      2 => 'geoserver',
      3 => 'cve-2024-36401',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => '/geoserver/',
      ),
      1 => 
      array (
        'in' => 'request',
        'regex' => '(?:exec\\(|Runtime|ProcessBuilder|Strings\\.|geoserver.{0,40}(?:ows|wfs|wms).{0,60}(?:exec|`))',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/xml; charset=UTF-8',
      ),
      'body' => '<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport version="2.0.0" xmlns:ows="http://www.opengis.net/ows/1.1">
  <ows:Exception exceptionCode="NoApplicableCode">
    <ows:ExceptionText>uid=0(root) gid=0(root) groups=0(root)</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
',
    ),
  ),
  25 => 
  array (
    'id' => 'attack-fortios-40684',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'fortinet',
      2 => 'fortios',
      3 => 'auth-bypass',
      4 => 'cve-2022-40684',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => '/api/v2/cmdb/system/admin',
      ),
      1 => 
      array (
        'in' => 'header:Forwarded',
        'contains' => 'for=',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/json',
      ),
      'body' => '{"http_method":"GET","results":[{"name":"admin","accprofile":"super_admin","trusthost1":"0.0.0.0 0.0.0.0","q_origin_key":"admin"}],"vdom":"root","path":"system","name":"admin","status":"success","http_status":200}
',
    ),
  ),
  26 => 
  array (
    'id' => 'attack-ivanti-21887',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'ivanti',
      2 => 'connect-secure',
      3 => 'rce',
      4 => 'cve-2023-46805',
      5 => 'cve-2024-21887',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '/api/v1/(?:totp/user-backup-code|license/keys-status|system/system-information)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/json',
      ),
      'body' => '{"web_server_version":"22.6R2","system":"Linux","result":"uid=0(root) gid=0(root) groups=0(root)\\n"}
',
    ),
  ),
  27 => 
  array (
    'id' => 'attack-citrix-bleed-4966',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'citrix',
      2 => 'netscaler',
      3 => 'memory-leak',
      4 => 'cve-2023-4966',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'contains' => '/oauth/idp/.well-known/openid-configuration',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/json; charset=utf-8',
      ),
      'body' => '{"issuer":"https://gateway.example.com/oauth/idp","authorization_endpoint":"https://gateway.example.com/oauth/idp/login"}
{{fake.bleed:hex:60}}{{fake.bleed2:hex:60}}
',
    ),
  ),
  28 => 
  array (
    'id' => 'attack-webshell-panel',
    'severity' => 'critical',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'webshell',
      2 => 'backdoor',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'request',
        'regex' => '(?:/(?:c99|wso|r57|b374k|shell|cmd|alfa|indoxploit)\\.php|(?:^|[?&\\s])(?:cmd|command|exec|shell_exec|passthru)=)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'text/html; charset=utf-8',
      ),
      'body' => '<html><head><title>Shell</title></head><body bgcolor="black" text="green">
<b>uname:</b> Linux web01 5.15.0 x86_64 GNU/Linux<br>
<b>user:</b> uid=33(www-data) gid=33(www-data) groups=33(www-data)<br>
<pre>$ id
uid=33(www-data) gid=33(www-data) groups=33(www-data)
$ </pre>
</body></html>
',
    ),
  ),
  29 => 
  array (
    'id' => 'attack-spring-actuator',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'spring-boot',
      2 => 'actuator',
      3 => 'exposure',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'regex' => '/actuator(?:/(?:env|health|configprops|mappings|beans|info))?/?$',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/vnd.spring-boot.actuator.v3+json',
      ),
      'body' => '{"_links":{"self":{"href":"http://localhost:8080/actuator","templated":false},"health":{"href":"http://localhost:8080/actuator/health"},"env":{"href":"http://localhost:8080/actuator/env"},"configprops":{"href":"http://localhost:8080/actuator/configprops"},"mappings":{"href":"http://localhost:8080/actuator/mappings"}},"propertySources":[{"name":"applicationConfig","properties":{"spring.datasource.password":{"value":"{{fake.springdb:hex:20}}"},"spring.mail.password":{"value":"{{fake.springmail:hex:16}}"}}}]}
',
    ),
  ),
  30 => 
  array (
    'id' => 'attack-cloud-imds',
    'severity' => 'high',
    'tags' => 
    array (
      0 => 'attack',
      1 => 'ssrf',
      2 => 'cloud-metadata',
      3 => 'imds',
    ),
    'status' => 200,
    'match' => 
    array (
      0 => 
      array (
        'in' => 'path',
        'regex' => '(?:/latest/meta-data/iam/security-credentials|/latest/dynamic/instance-identity|/computeMetadata/v1/|/metadata/instance)',
      ),
    ),
    'response' => 
    array (
      'headers' => 
      array (
        'Content-Type' => 'application/json',
      ),
      'body' => '{
  "Code" : "Success",
  "Type" : "AWS-HMAC",
  "AccessKeyId" : "ASIA{{fake.imdsak:hexupper:16}}",
  "SecretAccessKey" : "{{fake.imdssecret:b64:40}}",
  "Token" : "{{fake.imdstoken:b64:100}}",
  "Expiration" : "2030-01-01T00:00:00Z"
}
',
    ),
  ),
);
