<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-routes` — DO NOT EDIT.

return array (
  'templates' => 
  array (
    'route-ai-ollama-ps' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'ai-recon',
        1 => 'exposure',
        2 => 'appliance',
      ),
      'name' => 'Exposed Ollama running models',
    ),
    'route-ai-ollama-tags' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'ai-recon',
        1 => 'exposure',
        2 => 'appliance',
      ),
      'name' => 'Exposed Ollama model list',
    ),
    'route-vcs-head' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git HEAD (.git/HEAD)',
    ),
    'route-vcs-packed-refs' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git packed-refs (.git/packed-refs)',
    ),
    'route-vcs-refs-main' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git ref (.git/refs/heads/main)',
    ),
    'route-vcs-description' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git description (.git/description)',
    ),
    'route-vcs-commit-msg' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git commit message (.git/COMMIT_EDITMSG)',
    ),
    'route-vcs-exclude' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git exclude (.git/info/exclude)',
    ),
    'route-vcs-info-refs' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'git',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed git info/refs (.git/info/refs)',
    ),
    'route-vcs-svn-entries' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'subversion',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed Subversion entries (.svn/entries)',
    ),
    'route-vcs-hg-requires' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'mercurial',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed Mercurial requires (.hg/requires)',
    ),
    'route-basic-auth' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'basic-auth',
        1 => '401',
        2 => 'exposure',
      ),
      'name' => 'Basic Auth challenge',
    ),
    'route-credentials-txt' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'credentials',
        2 => 'secrets',
      ),
      'name' => 'Exposed credentials.txt',
    ),
    'route-terraform-tfstate' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'terraform',
        2 => 'secrets',
      ),
      'name' => 'Exposed terraform.tfstate',
    ),
    'route-users-csv' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'pii',
        2 => 'credentials',
      ),
      'name' => 'Exposed users.csv',
    ),
    'route-sql-backup' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'database',
        2 => 'backup',
      ),
      'name' => 'Exposed SQL backup',
    ),
    'route-dotaws-listing' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cloud',
        2 => 'aws',
        3 => 'directory-listing',
      ),
      'name' => 'Exposed .aws directory listing',
    ),
    'route-aws-cli-credentials' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cloud',
        2 => 'aws',
        3 => 'credentials',
      ),
      'name' => 'Exposed AWS CLI credentials',
    ),
    'route-aws-cli-config' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cloud',
        2 => 'aws',
        3 => 'config',
      ),
      'name' => 'Exposed AWS CLI config',
    ),
    'route-phpmyadmin' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'panel',
        2 => 'exposure',
      ),
      'name' => 'phpMyAdmin login',
    ),
    'route-phpmyadmin-css' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'panel',
        2 => 'asset',
      ),
      'name' => 'phpMyAdmin theme stylesheet',
    ),
    'route-ai-claude-json' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Claude Code config (.claude.json)',
    ),
    'route-ai-claude-desktop' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Claude Desktop config',
    ),
    'route-ai-mcp-json' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed editor MCP config',
    ),
    'route-ai-continue' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Continue config',
    ),
    'route-ai-aider' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed aider config',
    ),
    'route-ai-copilot-token' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Copilot token endpoint',
    ),
    'route-ai-openai-models' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed OpenAI-compatible models list',
    ),
    'route-mcp-endpoint' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'mcp',
        3 => 'appliance',
      ),
      'name' => 'MCP Streamable-HTTP endpoint',
    ),
    'route-llm-auth' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'llm-gateway',
        3 => 'appliance',
      ),
      'name' => 'LLM gateway auth required',
    ),
    'route-ai-ollama-version' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'ai-recon',
        1 => 'exposure',
        2 => 'appliance',
      ),
      'name' => 'Exposed Ollama server version',
    ),
    'route-config-php' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed application config (config.php)',
    ),
    'route-envfile-prod' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.production)',
    ),
    'route-secrets-json' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed secrets.json',
    ),
    'route-docker-compose' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed docker-compose.yml',
    ),
    'route-application-properties' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed Spring properties (application.properties)',
    ),
    'route-envfile-local' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.local)',
    ),
    'route-envfile-dev' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.development)',
    ),
    'route-envfile-staging' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.staging)',
    ),
    'route-envfile-test' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.test)',
    ),
    'route-envfile-bak' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.bak)',
    ),
    'route-envfile-php-src' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
        3 => 'source-leak',
      ),
      'name' => 'Exposed environment file source (.env.php)',
    ),
    'route-envfile-laravel' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (/laravel/.env)',
    ),
    'route-wp-debug-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed WordPress debug log (debug.log)',
    ),
    'route-php-error-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed PHP error log (error_log)',
    ),
    'route-laravel-log-alt' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed Laravel log (laravel.log)',
    ),
    'route-nginx-error-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed nginx error log (error.log)',
    ),
    'route-nginx-access-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed nginx access log (access.log)',
    ),
    'route-apache-error-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed Apache error log (error.log)',
    ),
    'route-apache-access-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed Apache access log (access.log)',
    ),
    'route-app-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed application log (app.log)',
    ),
    'route-catalina-out' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed Tomcat log (catalina.out)',
    ),
    'route-swagger-json-doc' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'openapi',
        3 => 'discovery',
      ),
      'name' => 'Exposed OpenAPI/Swagger document',
    ),
    'route-swagger2-apidocs' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'swagger',
        3 => 'discovery',
      ),
      'name' => 'Exposed Swagger 2.0 document',
    ),
    'route-swagger-yaml-doc' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'openapi',
        3 => 'discovery',
      ),
      'name' => 'Exposed OpenAPI document (YAML)',
    ),
    'route-swagger-ui-html' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'swagger-ui',
        3 => 'discovery',
      ),
      'name' => 'Exposed Swagger UI',
    ),
    'route-wp-json' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API index',
    ),
    'route-api-v2' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'discovery',
      ),
      'name' => 'Exposed REST API index (/api/v2)',
    ),
    'route-wp-json-v2-users' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API users',
    ),
    'route-wp-json-v2-posts' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API posts',
    ),
    'route-wp-json-v2-pages' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API pages',
    ),
    'route-wp-json-v2-comments' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API comments',
    ),
    'route-wp-json-v2-media' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API media',
    ),
    'route-wp-json-v2-categories' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API categories',
    ),
    'route-wp-json-v2-tags' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API tags',
    ),
    'route-wp-json-v2-types' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API types',
    ),
    'route-wp-json-v2-statuses' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API statuses',
    ),
    'route-wp-json-v2-settings' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'WordPress REST API settings (auth required)',
    ),
    'route-nextjs' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'nextjs',
        1 => 'react',
        2 => 'rsc',
        3 => 'framework',
        4 => 'discovery',
      ),
      'name' => 'Next.js App Router site',
    ),
    'route-phpmyadmin-changelog' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'version',
        2 => 'disclosure',
      ),
      'name' => 'phpMyAdmin ChangeLog (version disclosure)',
    ),
    'route-phpmyadmin-readme' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'version',
        2 => 'disclosure',
      ),
      'name' => 'phpMyAdmin README (version disclosure)',
    ),
    'route-phpmyadmin-doc' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'version',
        2 => 'disclosure',
      ),
      'name' => 'phpMyAdmin documentation (version disclosure)',
    ),
    'route-grafana-health' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'grafana',
        1 => 'health',
        2 => 'version',
        3 => 'disclosure',
      ),
      'name' => 'Grafana health (version disclosure)',
    ),
    'route-grafana-login' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'grafana',
        1 => 'panel',
        2 => 'login',
        3 => 'exposure',
      ),
      'name' => 'Grafana login',
    ),
    'route-jenkins-apijson' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'jenkins',
        1 => 'api',
        2 => 'version',
        3 => 'disclosure',
      ),
      'name' => 'Jenkins API root (version disclosure)',
    ),
    'route-pgadmin-login' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'pgadmin',
        1 => 'panel',
        2 => 'login',
        3 => 'exposure',
      ),
      'name' => 'pgAdmin 4 login',
    ),
    'route-cpanel-login' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'cpanel',
        1 => 'panel',
        2 => 'login',
        3 => 'exposure',
      ),
      'name' => 'cPanel login',
    ),
    'route-whm-login' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'whm',
        1 => 'cpanel',
        2 => 'panel',
        3 => 'login',
        4 => 'exposure',
      ),
      'name' => 'WHM login',
    ),
    'route-phppgadmin-intro' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'phppgadmin',
        1 => 'postgres',
        2 => 'panel',
        3 => 'version',
        4 => 'disclosure',
      ),
      'name' => 'phpPgAdmin intro (version disclosure)',
    ),
    'route-grafana-favicon' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'grafana',
        1 => 'favicon',
        2 => 'exposure',
      ),
      'name' => 'Grafana favicon',
    ),
    'route-phpmyadmin-favicon' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'favicon',
        2 => 'exposure',
      ),
      'name' => 'phpMyAdmin favicon',
    ),
    'route-jenkins-favicon' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'jenkins',
        1 => 'favicon',
        2 => 'exposure',
      ),
      'name' => 'Jenkins favicon',
    ),
    'route-tomcat-favicon' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'tomcat',
        1 => 'favicon',
        2 => 'exposure',
      ),
      'name' => 'Tomcat favicon',
    ),
    'route-neutral-favicon' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'favicon',
        1 => 'favicon',
        2 => 'exposure',
      ),
      'name' => 'Neutral favicon',
    ),
    'route-vcs-cvs-entries' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'vcs',
        2 => 'cvs',
        3 => 'source-disclosure',
      ),
      'name' => 'Exposed CVS/Entries',
    ),
    'route-typo3conf-listing' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cms',
        2 => 'typo3',
        3 => 'directory-listing',
      ),
      'name' => 'Exposed TYPO3 typo3conf directory listing',
    ),
    'route-typo3conf-localconf' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cms',
        2 => 'typo3',
        3 => 'config-disclosure',
        4 => 'secrets',
      ),
      'name' => 'Exposed TYPO3 localconf.php',
    ),
    'route-phpinfo' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'recon',
        1 => 'phpinfo',
        2 => 'exposure',
      ),
      'name' => 'PHP info page disclosure',
    ),
  ),
  'routes' => 
  array (
    'GET /api/ps' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"models"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-ollama-ps',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-ollama-ps',
        ),
        'w' => 1000,
      ),
    ),
    'GET /api/tags' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"models"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-ollama-tags',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-ollama-tags',
        ),
        'w' => 1000,
      ),
    ),
    'GET /.git/HEAD' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ref: refs/heads/',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-head',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-head',
        ),
      ),
    ),
    'GET /.git/packed-refs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'refs/remotes/origin/',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-packed-refs',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-packed-refs',
        ),
      ),
    ),
    'GET /.git/refs/heads/main' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-refs-main',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-refs-main',
        ),
      ),
    ),
    'GET /.git/description' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Unnamed repository',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-description',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-description',
        ),
      ),
    ),
    'GET /.git/COMMIT_EDITMSG' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-commit-msg',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-commit-msg',
        ),
      ),
    ),
    'GET /.git/info/exclude' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'git ls-files --others',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-exclude',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-exclude',
        ),
      ),
    ),
    'GET /.git/info/refs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'refs/heads/',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-info-refs',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-info-refs',
        ),
      ),
    ),
    'GET /.svn/entries' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'dir',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-svn-entries',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-svn-entries',
        ),
      ),
    ),
    'GET /.hg/requires' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'revlogv1',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-hg-requires',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-hg-requires',
        ),
      ),
    ),
    'GET /private/' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'Authorization Required',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-basic-auth',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-basic-auth',
        ),
        'th' => 
        array (
          'WWW-Authenticate' => 
          array (
            0 => 'Basic realm=',
          ),
        ),
      ),
    ),
    'GET /credentials.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /creds.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /backup/credentials.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /.terraform/terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /infra/terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /export/users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /backup/users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /backup.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /database.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /dump.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /db_backup.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /.aws' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Index of',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-dotaws-listing',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-dotaws-listing',
        ),
      ),
    ),
    'GET /.aws/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Index of',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-dotaws-listing',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-dotaws-listing',
        ),
      ),
    ),
    'GET /.aws/credentials' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'aws_access_key_id',
          1 => 'aws_secret_access_key',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-aws-cli-credentials',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-aws-cli-credentials',
        ),
        'w' => 1000,
      ),
    ),
    'GET /.aws/config' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[default]',
          1 => 'output = json',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-aws-cli-config',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-aws-cli-config',
        ),
        'w' => 1000,
      ),
    ),
    'GET /phpmyadmin/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpMyAdmin/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /pma/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpmyadmin/index.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpmyadmin/phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /phpMyAdmin/phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /pma/phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /.claude.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-claude-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-claude-json',
        ),
      ),
    ),
    'GET /claude_desktop_config.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-claude-desktop',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-claude-desktop',
        ),
      ),
    ),
    'GET /.cursor/mcp.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-mcp-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-mcp-json',
        ),
      ),
    ),
    'GET /.vscode/mcp.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-mcp-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-mcp-json',
        ),
      ),
    ),
    'GET /.continue/config.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"models"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-continue',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-continue',
        ),
      ),
    ),
    'GET /.aider.conf.yml' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'anthropic-api-key',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-aider',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-aider',
        ),
      ),
    ),
    'GET /copilot_internal/v2/token' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'annotations_enabled',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-copilot-token',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-copilot-token',
        ),
      ),
    ),
    'GET /openai/models' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"object":"list"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-openai-models',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-openai-models',
        ),
      ),
    ),
    'GET /mcp' => 
    array (
      0 => 
      array (
        's' => 400,
        'bw' => 
        array (
          0 => 'jsonrpc',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-mcp-endpoint',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-mcp-endpoint',
        ),
      ),
    ),
    'GET /api/mcp' => 
    array (
      0 => 
      array (
        's' => 400,
        'bw' => 
        array (
          0 => 'jsonrpc',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-mcp-endpoint',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-mcp-endpoint',
        ),
      ),
    ),
    'GET /v1/chat' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'invalid_request_error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-llm-auth',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-llm-auth',
        ),
      ),
    ),
    'GET /v1/completions' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'invalid_request_error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-llm-auth',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-llm-auth',
        ),
      ),
    ),
    'GET /api/version' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-ollama-version',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-ollama-version',
        ),
        'w' => 1000,
      ),
    ),
    'GET /config.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'DB_PASSWORD',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-config-php',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-config-php',
        ),
      ),
    ),
    'GET /.env.production' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-prod',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-prod',
        ),
      ),
    ),
    'GET /secrets.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'secretKey',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-secrets-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-secrets-json',
        ),
      ),
    ),
    'GET /docker-compose.yml' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'services:',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-docker-compose',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-docker-compose',
        ),
      ),
    ),
    'GET /application.properties' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'spring.datasource',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-application-properties',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-application-properties',
        ),
      ),
    ),
    'GET /.env.local' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-local',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-local',
        ),
      ),
    ),
    'GET /.env.development' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-dev',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-dev',
        ),
      ),
    ),
    'GET /.env.staging' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-staging',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-staging',
        ),
      ),
    ),
    'GET /.env.test' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-test',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-test',
        ),
      ),
    ),
    'GET /.env.bak' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-bak',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-bak',
        ),
      ),
    ),
    'GET /.env.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-php-src',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-php-src',
        ),
      ),
    ),
    'GET /laravel/.env' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-laravel',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-laravel',
        ),
      ),
    ),
    'GET /wp-content/debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Notice',
          1 => 'PHP Warning',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-debug-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-debug-log',
        ),
      ),
    ),
    'GET /wp-content/uploads/debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Notice',
          1 => 'PHP Warning',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-debug-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-debug-log',
        ),
      ),
    ),
    'GET /debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Notice',
          1 => 'PHP Warning',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-debug-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-debug-log',
        ),
      ),
    ),
    'GET /error_log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /php_errors.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /php_error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /logs/error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /laravel.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'production.ERROR',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-laravel-log-alt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-laravel-log-alt',
        ),
      ),
    ),
    'GET /logs/laravel.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'production.ERROR',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-laravel-log-alt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-laravel-log-alt',
        ),
      ),
    ),
    'GET /var/log/nginx/error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[error]',
          1 => 'upstream',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nginx-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-nginx-error-log',
        ),
      ),
    ),
    'GET /nginx_error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[error]',
          1 => 'upstream',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nginx-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-nginx-error-log',
        ),
      ),
    ),
    'GET /var/log/nginx/access.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"GET /',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nginx-access-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-nginx-access-log',
        ),
      ),
    ),
    'GET /var/log/apache2/error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[core:error]',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-apache-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-apache-error-log',
        ),
      ),
    ),
    'GET /var/log/httpd/error_log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[core:error]',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-apache-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-apache-error-log',
        ),
      ),
    ),
    'GET /var/log/apache2/access.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"GET /',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-apache-access-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-apache-access-log',
        ),
      ),
    ),
    'GET /app.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /logs/app.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /server.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /logs/debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /catalina.out' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'SEVERE',
          1 => 'java.lang.',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-catalina-out',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-catalina-out',
        ),
      ),
    ),
    'GET /swagger.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /api/swagger.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /v3/api-docs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /api-docs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /.well-known/openapi.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /v2/api-docs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"swagger":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger2-apidocs',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger2-apidocs',
        ),
      ),
    ),
    'GET /openapi.yaml' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'openapi:',
          1 => 'paths:',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-yaml-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-yaml-doc',
        ),
      ),
    ),
    'GET /swagger-ui.html' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /swagger-ui/index.html' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /swagger' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /api/__swagger__/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /wp-json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'namespaces',
          1 => 'routes',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json',
        ),
      ),
    ),
    'GET /api/v2' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'endpoints',
          1 => 'version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-api-v2',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-api-v2',
        ),
      ),
    ),
    'GET /wp-json/wp/v2/users' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"slug"',
          1 => '"avatar_urls"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-users',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-users',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/users/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"slug"',
          1 => '"avatar_urls"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-users',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-users',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/posts' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"post"',
          1 => '"rendered"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-posts',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-posts',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/posts/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"post"',
          1 => '"rendered"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-posts',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-posts',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/pages' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"page"',
          1 => '"rendered"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-pages',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-pages',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/pages/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"page"',
          1 => '"rendered"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-pages',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-pages',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/comments' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"comment"',
          1 => '"author_name"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-comments',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-comments',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/comments/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"comment"',
          1 => '"author_name"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-comments',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-comments',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/media' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"attachment"',
          1 => '"media_type":"image"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-media',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-media',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/media/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"type":"attachment"',
          1 => '"media_type":"image"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-media',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-media',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/categories' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"taxonomy":"category"',
          1 => '"slug"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-categories',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-categories',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/categories/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"taxonomy":"category"',
          1 => '"slug"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-categories',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-categories',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/tags' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"taxonomy":"post_tag"',
          1 => '"slug"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-tags',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-tags',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/tags/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"taxonomy":"post_tag"',
          1 => '"slug"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-tags',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-tags',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/types' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"rest_base":"posts"',
          1 => '"slug":"post"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-types',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-types',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/types/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"rest_base":"posts"',
          1 => '"slug":"post"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-types',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-types',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/statuses' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"slug":"publish"',
          1 => '"queryable"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-statuses',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-statuses',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/statuses/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"slug":"publish"',
          1 => '"queryable"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-statuses',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-statuses',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/settings' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => '"rest_forbidden"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-settings',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-settings',
        ),
        'w' => 1000,
      ),
    ),
    'GET /wp-json/wp/v2/settings/' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => '"rest_forbidden"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json-v2-settings',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json-v2-settings',
        ),
        'w' => 1000,
      ),
    ),
    'GET /' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'self.__next_f',
          1 => '_next/static',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nextjs',
        'sev' => 'info',
        'sig' => 1,
        't' => 
        array (
          0 => 'route-nextjs',
        ),
      ),
    ),
    'GET /phpmyadmin/ChangeLog' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
          1 => 'ChangeLog',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-changelog',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-changelog',
        ),
      ),
    ),
    'GET /phpmyadmin/README' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-readme',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-readme',
        ),
      ),
    ),
    'GET /phpmyadmin/doc/html/index.html' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-doc',
        ),
      ),
    ),
    'GET /api/health' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'commit',
          1 => 'version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-health',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-health',
        ),
      ),
    ),
    'GET /grafana/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Grafana',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-login',
        ),
      ),
    ),
    'GET /grafana/login' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Grafana',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-login',
        ),
      ),
    ),
    'GET /api/json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'jobs',
          1 => 'mode',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-jenkins-apijson',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-jenkins-apijson',
        ),
      ),
    ),
    'GET /pgadmin4/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'pgAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-pgadmin-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-pgadmin-login',
        ),
      ),
    ),
    'GET /pgadmin4/login' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'pgAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-pgadmin-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-pgadmin-login',
        ),
      ),
    ),
    'GET /cpanel' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'cPanel',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-cpanel-login',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-cpanel-login',
        ),
      ),
    ),
    'GET /whm' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'WHM',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-whm-login',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-whm-login',
        ),
      ),
    ),
    'GET /phppgadmin/intro.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpPgAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phppgadmin-intro',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phppgadmin-intro',
        ),
      ),
    ),
    'GET /grafana/favicon.ico' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-favicon',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-favicon',
        ),
        'bin' => 1,
      ),
    ),
    'GET /phpmyadmin/favicon.ico' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-favicon',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-favicon',
        ),
        'bin' => 1,
      ),
    ),
    'GET /jenkins/favicon.ico' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-jenkins-favicon',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-jenkins-favicon',
        ),
        'bin' => 1,
      ),
    ),
    'GET /manager/favicon.ico' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-tomcat-favicon',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-tomcat-favicon',
        ),
        'bin' => 1,
      ),
    ),
    'GET /favicon.ico' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-neutral-favicon',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-neutral-favicon',
        ),
        'w' => 25,
        'bin' => 1,
      ),
    ),
    'GET /CVS/Entries' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '/index.php/',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-vcs-cvs-entries',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-vcs-cvs-entries',
        ),
      ),
    ),
    'GET /typo3conf/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Index of',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-typo3conf-listing',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-typo3conf-listing',
        ),
      ),
    ),
    'GET /typo3conf' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Index of',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-typo3conf-listing',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-typo3conf-listing',
        ),
      ),
    ),
    'GET /typo3conf/localconf.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '$typo_db_password',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-typo3conf-localconf',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-typo3conf-localconf',
        ),
      ),
    ),
    'GET /phpinfo.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpinfo()',
          1 => 'PHP Version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpinfo',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpinfo',
        ),
        'w' => 8,
      ),
    ),
    'GET /phpinfo' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpinfo()',
          1 => 'PHP Version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpinfo',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpinfo',
        ),
        'w' => 8,
      ),
    ),
    'GET /info.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpinfo()',
          1 => 'PHP Version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpinfo',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpinfo',
        ),
        'w' => 8,
      ),
    ),
  ),
);
