<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-routes` — DO NOT EDIT.

return array (
  0 => 
  array (
    'id' => 'route-git-config',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'git-config',
        1 => 'git',
      ),
    ),
    'body' => '[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://git.example.com/internal/{{pick:app,platform,api,web,core}}.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "{{pick:main,master,develop,release}}"]
	remote = origin
	merge = refs/heads/{{pick:main,master,develop,release}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  1 => 
  array (
    'id' => 'route-dotenv',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'dotenv',
        1 => 'env-',
        2 => 'exposed-config',
        3 => 'environment',
      ),
    ),
    'body' => 'APP_NAME={{pick:Acme,Platform,Portal,Service}}
APP_ENV=production
APP_KEY=base64:{{fake.appkey:hex:32}}==
APP_DEBUG=false
APP_URL=https://app.example.com

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=app_production
DB_USERNAME=app_ro
DB_PASSWORD={{fake.dbpass:hex:24}}

MAIL_MAILER=smtp
MAIL_HOST=smtp.example.com
MAIL_PORT=587
MAIL_USERNAME=no-reply@example.com
MAIL_PASSWORD={{fake.mail:hex:20}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  2 => 
  array (
    'id' => 'route-xmlrpc',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'xmlrpc',
        1 => 'xml-rpc',
      ),
    ),
    'body' => '<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param>
      <value>
      <array><data>
      <value><string>system.multicall</string></value>
      <value><string>system.listMethods</string></value>
      <value><string>system.getCapabilities</string></value>
      <value><string>wp.getUsersBlogs</string></value>
      <value><string>wp.getPost</string></value>
      <value><string>wp.getPosts</string></value>
      <value><string>wp.getOptions</string></value>
      <value><string>pingback.ping</string></value>
      </data></array>
      </value>
    </param>
  </params>
</methodResponse>
',
    'headers' => 
    array (
      'Content-Type' => 'text/xml; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  3 => 
  array (
    'id' => 'route-wp-config',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'wpconfig-aws-keys',
        1 => 'aws-credentials',
        2 => 'wp-config',
      ),
    ),
    'body' => '<?php
/**
 * The base configuration for WordPress (backup copy).
 */

// ** Database settings ** //
define(\'DB_NAME\', \'{{pick:wp_prod,wordpress,wp_live,blog}}\');
define(\'DB_USER\', \'wp_app\');
define(\'DB_PASSWORD\', \'{{fake.dbpass:hex:24}}\');
define(\'DB_HOST\', \'127.0.0.1\');
define(\'DB_CHARSET\', \'utf8mb4\');

// ** WP Offload Media (Amazon S3) bucket credentials ** //
define(\'AS3CF_SETTINGS\', serialize(array(
    \'provider\'          => \'aws\',
    \'access-key-id\'     => \'AKIA{{fake.akid:hexupper:16}}\',
    \'secret-access-key\' => \'{{fake.awssecret:hex:40}}\',
    \'bucket\'            => \'media.example.com\',
    \'region\'            => \'us-east-1\',
)));

define(\'AUTH_SALT\', \'{{fake.authsalt:hex:48}}\');
$table_prefix = \'wp_\';
define(\'WP_DEBUG\', false);
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  4 => 
  array (
    'id' => 'route-wp-login',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'wordpress-login',
        1 => 'wp-enabled-registration',
        2 => 'wp-registration-enabled',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />
<title>Log In &lsaquo; {{pick:Example Site,Acme Blog,Company News,The Portal}} &#8212; WordPress</title>
<link rel=\'stylesheet\' href=\'https://blog.example.com/wp-includes/css/dist/block-library/style.min.css\' />
</head>
<body class="login no-js login-action-login wp-core-ui">
<div id="login">
<h1><a href="https://blog.example.com/">Example Site</a></h1>
<p class="message register">Register For This Site</p>
<form name="loginform" id="loginform" action="https://blog.example.com/wp-login.php" method="post">
<p><label>Username or Email Address<br />
<input type="text" name="log" class="input" /></label></p>
<p><label>Password<br />
<input type="password" name="pwd" class="input" /></label></p>
<p class="submit"><input type="submit" name="wp-submit" value="Log In" /></p>
</form>
<p id="nav">
<a href="https://blog.example.com/wp-login.php?action=register">Register</a> |
<a href="https://blog.example.com/wp-login.php?action=lostpassword">Lost your password?</a>
</p>
</div>
</body>
</html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'PHPSESSID',
  ),
  5 => 
  array (
    'id' => 'route-phpinfo',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'phpinfo',
        1 => 'php-info',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>phpinfo()</title></head>
<body>
<h1 class="p">PHP Version {{pick:8.1.27,8.2.18,7.4.33,8.0.30}}</h1>
<table>
<tr><td class="e">System</td><td class="v">Linux {{pick:web01,app-node-1,php-fpm,srv-web}} 5.15.0 x86_64</td></tr>
<tr><td class="e">Server API</td><td class="v">FPM/FastCGI</td></tr>
<tr><td class="e">Document Root</td><td class="v">/var/www/example.com/public</td></tr>
<tr><td class="e">Loaded Configuration File</td><td class="v">/etc/php/php.ini</td></tr>
</table>
<h2>PHP Extension</h2>
<table>
<tr><td class="e">openssl</td><td class="v">enabled</td></tr>
<tr><td class="e">pdo_mysql</td><td class="v">enabled</td></tr>
</table>
<p>This output was generated by phpinfo().</p>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  6 => 
  array (
    'id' => 'route-htpasswd',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'htpasswd',
      ),
    ),
    'body' => 'admin:{SHA}{{fake.sha-admin:b64:28}}
deploy:{SHA}{{fake.sha-deploy:b64:28}}
backup:{SHA}{{fake.sha-backup:b64:28}}
webmaster:{SHA}{{fake.sha-webmaster:b64:28}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  7 => 
  array (
    'id' => 'route-apache-server-status',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'apache-server-status',
        1 => 'server-status',
        2 => 'server-info',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Apache Status</title></head><body>
<h1>Apache Server Status for status.example.com (via 192.0.2.10)</h1>
<dl>
<dt>Server Version: Apache/{{pick:2.4.58,2.4.52,2.4.41}} (Unix) OpenSSL/3.0</dt>
<dt>Server MPM: event</dt>
<dt>Server Built: Jan  1 2024</dt>
<dt>Current Time: Monday, 01-Jan-2024 00:00:00 UTC</dt>
<dt>Server uptime: {{pick:3 days,11 hours,27 days}}</dt>
<dt>Total accesses: 10423 - Total Traffic: 84.2 MB</dt>
</dl>
<pre>
Srv  Client          VHost                Request
0-0  198.51.100.24   www.example.com      GET / HTTP/1.1
1-0  203.0.113.7     www.example.com      GET /favicon.ico HTTP/1.1
</pre>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  8 => 
  array (
    'id' => 'route-package-json',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'package-json',
      ),
    ),
    'body' => '{
  "name": "@example/{{pick:web-app,dashboard,storefront,admin-ui}}",
  "version": "{{pick:1.4.2,3.0.1,2.11.0,0.9.7}}",
  "private": true,
  "description": "Internal web frontend.",
  "scripts": {
    "build": "vite build",
    "test": "vitest run"
  },
  "dependencies": {
    "react": "^18.2.0",
    "axios": "^1.6.0"
  },
  "devDependencies": {
    "vite": "^5.0.0"
  }
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  9 => 
  array (
    'id' => 'route-ssh-private-key',
    'match' => 
    array (
      'body_word_contains' => 
      array (
        0 => 'PRIVATE KEY',
      ),
    ),
    'body' => '-----BEGIN RSA PRIVATE KEY-----
{{fake.pem-a:b64:64}}
{{fake.pem-b:b64:64}}
{{fake.pem-c:b64:64}}
{{fake.pem-d:b64:64}}
-----END RSA PRIVATE KEY-----
',
    'headers' => 
    array (
      'Content-Type' => 'application/x-pem-file',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  10 => 
  array (
    'id' => 'route-sql-dump',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'database-backup',
        1 => 'sql-dump',
        2 => 'sql-backup',
        3 => 'mysql-dump',
        4 => 'db-dump',
      ),
    ),
    'body' => '-- MySQL dump 10.13  Distrib 8.0.36
--
-- Host: localhost    Database: {{pick:froxlor,app_prod,cms,billing}}
-- ------------------------------------------------------

DROP TABLE IF EXISTS `panel_admins`;
CREATE TABLE `panel_admins` (
  `adminid` int(11) NOT NULL AUTO_INCREMENT,
  `loginname` varchar(50) NOT NULL DEFAULT \'\',
  `password` varchar(255) NOT NULL DEFAULT \'\',
  `email` varchar(255) NOT NULL DEFAULT \'\',
  PRIMARY KEY (`adminid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `panel_admins` VALUES (1,\'admin\',\'$2y$10${{fake.adminpw:hex:53}}\',\'admin@example.com\');
',
    'headers' => 
    array (
      'Content-Type' => 'application/sql',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '--',
    ),
  ),
  11 => 
  array (
    'id' => 'route-weblogic',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'weblogic-login',
        1 => 'weblogic',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Oracle WebLogic Server Administration Console</title></head>
<body>
<h1>Oracle WebLogic Server Administration Console</h1>
<p>WebLogic Server Version: 10.3.6.0</p>
<form action="/console/j_security_check" method="post">
<label>Username</label><input name="j_username" type="text" />
<label>Password</label><input name="j_password" type="password" />
<input type="submit" value="Login" />
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'JSESSIONID',
  ),
  12 => 
  array (
    'id' => 'route-exchange-owa',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'microsoft-exchange-panel',
        1 => 'exchange-admin',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Outlook</title></head>
<body>
<div id="loginArea">
<h1>Exchange Admin Center</h1>
<form action="/owa/auth.owa" method="POST">
<input name="username" type="text" placeholder="domain\\user" />
<input name="password" type="password" />
<input type="submit" value="sign in" />
</form>
</div>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'ASP.NET_SessionId',
  ),
  13 => 
  array (
    'id' => 'route-adminer',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'adminer-panel',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Adminer</title></head>
<body>
<h1>Adminer <span class="version">4.8.1</span></h1>
<form action="" method="post">
<p>System <select name="auth[driver]"><option value="server">MySQL</option></select></p>
<p>Server <input name="auth[server]" value="localhost" /></p>
<p>Username <input name="auth[username]" /></p>
<p>Password <input type="password" name="auth[password]" /></p>
<p>Database <input name="auth[db]" /></p>
<p><input type="submit" value="Login" /></p>
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'PHPSESSID',
  ),
  14 => 
  array (
    'id' => 'route-joomla',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'joomla-panel',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head>
<meta name="generator" content="Joomla! - Open Source Content Management" />
<title>Administration - Login</title>
</head>
<body>
<form action="/administrator/index.php" method="post">
<input name="username" type="text" />
<input name="passwd" type="password" />
<button type="submit">Log in</button>
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'PHPSESSID',
  ),
  15 => 
  array (
    'id' => 'route-wp-readme',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'wordpress-readme-file',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>WordPress &#8250; ReadMe</title></head>
<body>
<h1 id="logo">WordPress</h1>
<p>Version {{pick:6.4.2,6.3.1,5.9.3,6.2.2}}</p>
<h2>Installation</h2>
<p>Famous 5-minute install.</p>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  16 => 
  array (
    'id' => 'route-citrix',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'citrix-adc-gateway-panel',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Citrix Gateway</title></head>
<body>
<div class="CTXMSAM_LogonFont">Citrix Gateway</div>
<script type="text/javascript">var _ctxstxt_CitrixCopyright = "Citrix Systems, Inc. All rights reserved.";</script>
<form method="post" action="/cgi/login">
<input name="login" type="text" />
<input name="passwd" type="password" />
<input type="submit" value="Log On" />
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'NSC_AAAC',
  ),
  17 => 
  array (
    'id' => 'route-directory-listing',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'directory-listing',
      ),
    ),
    'body' => '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html><head><title>Index of /backup</title></head>
<body>
<h1>Index of /backup</h1>
<pre><a href="?C=N;O=D">Name</a>  <a href="?C=M;O=A">Last modified</a>  <a href="?C=S;O=A">Size</a>
<hr>
<a href="../">Parent Directory</a>                       -
<a href="database.sql">database.sql</a>      2024-01-01 12:00  4.2M
<a href="config.php.bak">config.php.bak</a>  2024-01-01 12:00  2.1K
<a href="www.tar.gz">www.tar.gz</a>          2024-01-01 12:00   18M
<hr></pre>
<address>Apache Server at localhost Port 80</address>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  18 => 
  array (
    'id' => 'route-django-admin',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'django-admin-panel',
        1 => 'default-django-page',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html lang="en"><head><title>Log in | Django site admin</title></head>
<body class="login">
<div id="container">
<div id="header"><h1 id="site-name">Django administration</h1></div>
<div id="content">
<form action="/admin/login/" method="post" id="login-form">
<div class="form-row"><label>Username:</label><input type="text" name="username" /></div>
<div class="form-row"><label>Password:</label><input type="password" name="password" /></div>
<div class="submit-row"><input type="submit" value="Log in" /></div>
</form>
</div>
</div>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'sessionid',
  ),
  19 => 
  array (
    'id' => 'route-tomcat-manager',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'apache-tomcat-exposed',
        1 => 'tomcat-default-login',
        2 => 'tomcat',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>/manager</title></head>
<body>
<h1>Tomcat Web Application Manager</h1>
<table>
<tr><th>Path</th><th>Version</th><th>Display Name</th><th>Running</th><th>Sessions</th></tr>
<tr><td>/</td><td>None</td><td>Welcome to Tomcat</td><td>true</td><td>0</td></tr>
<tr><td>/manager</td><td>None</td><td>Tomcat Manager Application</td><td>true</td><td>1</td></tr>
</table>
<h2>Server Information</h2>
<table>
<tr><th>Tomcat Version</th><th>JVM Version</th><th>OS Name</th></tr>
<tr><td>Apache Tomcat/{{pick:9.0.71,8.5.87,10.1.7}}</td><td>17.0.6+10</td><td>Linux</td></tr>
</table>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html;charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'JSESSIONID',
  ),
  20 => 
  array (
    'id' => 'route-basic-auth',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-basic-auth',
      ),
    ),
    'body' => '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head><title>401 Authorization Required</title></head>
<body><h1>Authorization Required</h1>
<p>This server could not verify that you are authorized to access the document requested.</p>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=iso-8859-1',
      'WWW-Authenticate' => 'Basic realm="Restricted Area"',
    ),
  ),
  21 => 
  array (
    'id' => 'route-credentials-txt',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-credentials-txt',
      ),
    ),
    'body' => '# production credentials — rotate quarterly
AWS_ACCESS_KEY_ID=AKIA{{fake.ak:hexupper:16}}
AWS_SECRET_ACCESS_KEY={{fake.aws:b64:40}}
DB_HOST=db.internal.example.com
DB_USER=admin
DB_PASSWORD={{fake.dbpass:hex:24}}
API_TOKEN={{fake.api:hex:40}}
SMTP_PASSWORD={{fake.smtp:hex:20}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  22 => 
  array (
    'id' => 'route-terraform-tfstate',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-terraform-tfstate',
      ),
    ),
    'body' => '{
  "version": 4,
  "terraform_version": "1.6.2",
  "serial": 42,
  "resources": [
    {
      "type": "aws_iam_access_key",
      "name": "deploy",
      "instances": [
        { "attributes": {
          "id": "AKIA{{fake.tfak:hexupper:16}}",
          "secret": "{{fake.tfsecret:b64:40}}",
          "user": "ci-deploy"
        } }
      ]
    }
  ]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  23 => 
  array (
    'id' => 'route-users-csv',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-users-csv',
      ),
    ),
    'body' => 'id,username,email,password_hash,role
1,admin,admin@example.com,$2y$10${{fake.u1:hex:53}},superadmin
2,jdoe,jane.doe@example.com,$2y$10${{fake.u2:hex:53}},editor
3,bsmith,bob.smith@example.com,$2y$10${{fake.u3:hex:53}},user
4,service,svc@example.com,$2y$10${{fake.u4:hex:53}},api
',
    'headers' => 
    array (
      'Content-Type' => 'text/csv; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  24 => 
  array (
    'id' => 'route-sql-backup',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-sql-backup',
      ),
    ),
    'body' => '-- MySQL dump 10.13  Distrib 8.0.36
-- Host: localhost    Database: {{pick:app_prod,cms,billing,shop}}
-- ------------------------------------------------------

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `users` VALUES (1,\'admin@example.com\',\'$2y$10${{fake.pw:hex:53}}\');
',
    'headers' => 
    array (
      'Content-Type' => 'application/sql',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '--',
    ),
  ),
  25 => 
  array (
    'id' => 'route-phpmyadmin',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-phpmyadmin',
      ),
    ),
    'body' => '<!DOCTYPE HTML>
<html lang="en"><head><title>phpMyAdmin</title>
<link rel="stylesheet" type="text/css" href="phpmyadmin.css.php" />
</head>
<body class="loginform">
<div class="container">
<h1>Welcome to phpMyAdmin</h1>
<form method="post" action="index.php" name="login_form" class="login">
<fieldset>
<legend>Log in</legend>
<label for="input_username">Username:</label>
<input type="text" name="pma_username" id="input_username" value="root" />
<label for="input_password">Password:</label>
<input type="password" name="pma_password" id="input_password" />
</fieldset>
<input type="submit" value="Go" id="input_go" />
</form>
<div class="footer">phpMyAdmin {{pick:5.2.1,5.1.3,4.9.7}}</div>
</div>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'phpMyAdmin',
  ),
);
