<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-params` — DO NOT EDIT.

return array (
  'schema' => 1,
  'buckets' => 
  array (
    '@fs' => 
    array (
      0 => 
      array (
        'id' => 'param-vite-fs',
        'severity' => 'high',
        'tags' => 
        array (
          0 => 'param',
          1 => 'vite',
          2 => 'lfi',
        ),
        'status' => 200,
        'method' => 'GET',
        'regex' => '^/@fs/(?P<path>.+)$',
        'captures' => 
        array (
          0 => 'path',
        ),
        'response' => 
        array (
          'headers' => 
          array (
            'Content-Type' => 'text/plain; charset=utf-8',
          ),
          'body' => '// requested path: /@fs/{{match.path}}
',
        ),
      ),
    ),
  ),
);
