<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-routes` — DO NOT EDIT.

return array (
  0 => 
  array (
    'id' => 'route-git-config',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'git-config',
        1 => 'git',
      ),
    ),
    'body' => '[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://git.example.com/internal/{{pick:app,platform,api,web,core}}.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "{{pick:main,master,develop,release}}"]
	remote = origin
	merge = refs/heads/{{pick:main,master,develop,release}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  1 => 
  array (
    'id' => 'route-dotenv',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'dotenv',
        1 => 'env-',
        2 => 'exposed-config',
        3 => 'environment',
      ),
      'body_word_contains' => 
      array (
        0 => 'APP_DEBUG=',
      ),
    ),
    'body' => 'APP_NAME={{pick:Acme,Northwind,Contoso,Fabrikam,Initech}}
APP_ENV=production
APP_KEY=base64:{{fake.app_key:b64:44}}
APP_DEBUG=false
APP_URL=https://app.example.com

LOG_CHANNEL=stack

DB_CONNECTION=pgsql
DB_HOST=db-{{fake.pghost:hex:6}}.cluster-cg{{fake.pgacct:hex:9}}.eu-west-1.rds.amazonaws.com
DB_PORT=5432
DB_DATABASE=app_production
DB_USERNAME=app_prod
DB_PASSWORD={{fake.pgpass:hex:24}}

REDIS_HOST=cache-{{fake.redishost:hex:6}}.0001.euw1.cache.amazonaws.com
REDIS_PORT=6379
REDIS_PASSWORD={{fake.redispass:hex:32}}

# AWS — S3 uploads + SES. The key pair is the persona identity\'s (not a shared 6-value pick), so
# this /.env discloses the SAME AWS key as /@fs/.env, /@fs/.aws/credentials and wp-config for a
# given deployment. Region stays eu-west-1 to agree with the RDS/ElastiCache hosts above.
AWS_ACCESS_KEY_ID={{persona.cloud.aws.accessKeyId}}
AWS_SECRET_ACCESS_KEY={{persona.cloud.aws.secretKey}}
AWS_DEFAULT_REGION=eu-west-1
AWS_BUCKET={{pick:acme,northwind,contoso,fabrikam,initech}}-prod-uploads

# Stripe — billing
STRIPE_KEY=pk_live_{{fake.stripe_pk:hex:24}}
STRIPE_SECRET=sk_live_{{fake.stripe_sk:hex:24}}
STRIPE_WEBHOOK_SECRET=whsec_{{fake.stripe_whsec:hex:32}}

# Mail — SendGrid
MAIL_MAILER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=apikey
SENDGRID_API_KEY=SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}

JWT_SECRET={{fake.jwtsecret:hex:64}}
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/T{{fake.slackt:hex:8}}/B{{fake.slackb:hex:8}}/{{fake.slacktok:hex:24}}
',
    'headers' => 
    array (
      'Content-Type' => 'application/octet-stream',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  2 => 
  array (
    'id' => 'route-xmlrpc',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'xmlrpc',
        1 => 'xml-rpc',
      ),
    ),
    'body' => '<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
  <params>
    <param>
      <value>
      <array><data>
      <value><string>system.multicall</string></value>
      <value><string>system.listMethods</string></value>
      <value><string>system.getCapabilities</string></value>
      <value><string>wp.getUsersBlogs</string></value>
      <value><string>wp.getPost</string></value>
      <value><string>wp.getPosts</string></value>
      <value><string>wp.getOptions</string></value>
      <value><string>pingback.ping</string></value>
      </data></array>
      </value>
    </param>
  </params>
</methodResponse>
',
    'headers' => 
    array (
      'Content-Type' => 'text/xml; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  3 => 
  array (
    'id' => 'route-wp-config',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'wpconfig-aws-keys',
        1 => 'aws-credentials',
        2 => 'wp-config',
      ),
    ),
    'body' => '<?php
/**
 * The base configuration for WordPress (backup copy).
 */

// ** Database settings ** //
define(\'DB_NAME\', \'{{pick:wp_prod,wordpress,wp_live,blog}}\');
define(\'DB_USER\', \'wp_app\');
define(\'DB_PASSWORD\', \'{{fake.dbpass:hex:24}}\');
define(\'DB_HOST\', \'wp-prod-db-{{fake.dbhost:hex:6}}.cluster-cg{{fake.dbacct:hex:9}}.us-east-1.rds.amazonaws.com\');
define(\'DB_CHARSET\', \'utf8mb4\');
define(\'DB_COLLATE\', \'\');

// ** WP Offload Media (Amazon S3) bucket credentials ** //
define(\'AS3CF_SETTINGS\', serialize(array(
    \'provider\'          => \'aws\',
    \'access-key-id\'     => \'{{persona.cloud.aws.accessKeyId}}\',
    \'secret-access-key\' => \'{{persona.cloud.aws.secretKey}}\',
    \'bucket\'            => \'media.example.com\',
    \'region\'            => \'us-east-1\',
)));

// ** WooCommerce Stripe Gateway ** //
define(\'WC_STRIPE_SECRET_KEY\', \'sk_live_{{fake.wcsk:hex:24}}\');

// ** SendGrid (WP Mail SMTP) ** //
define(\'SENDGRID_API_KEY\', \'SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}\');

// ** Authentication unique keys and salts ** //
define(\'AUTH_KEY\', \'{{fake.authkey:hex:64}}\');
define(\'AUTH_SALT\', \'{{fake.authsalt:hex:64}}\');

$table_prefix = \'wp_\';
define(\'WP_DEBUG\', false);
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  4 => 
  array (
    'id' => 'route-wp-login',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'wordpress-login',
        1 => 'wp-enabled-registration',
        2 => 'wp-registration-enabled',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8" />
<title>Log In &lsaquo; {{pick:Example Site,Acme Blog,Company News,The Portal}} &#8212; WordPress</title>
<link rel=\'stylesheet\' href=\'https://blog.example.com/wp-includes/css/dist/block-library/style.min.css\' />
</head>
<body class="login no-js login-action-login wp-core-ui">
<div id="login">
<h1><a href="https://blog.example.com/">Example Site</a></h1>
<p class="message register">Register For This Site</p>
<form name="loginform" id="loginform" action="https://blog.example.com/wp-login.php" method="post">
<p><label>Username or Email Address<br />
<input type="text" name="log" class="input" /></label></p>
<p><label>Password<br />
<input type="password" name="pwd" class="input" /></label></p>
<p class="submit"><input type="submit" name="wp-submit" value="Log In" /></p>
</form>
<p id="nav">
<a href="https://blog.example.com/wp-login.php?action=register">Register</a> |
<a href="https://blog.example.com/wp-login.php?action=lostpassword">Lost your password?</a>
</p>
</div>
</body>
</html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'PHPSESSID',
  ),
  5 => 
  array (
    'id' => 'route-phpinfo',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'phpinfo',
        1 => 'php-info',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>phpinfo()</title></head>
<body>
<h1 class="p">PHP Version {{pick:8.1.27,8.2.18,7.4.33,8.0.30}}</h1>
<table>
<tr><td class="e">System</td><td class="v">Linux {{pick:web01,app-node-1,php-fpm,srv-web}} 5.15.0 x86_64</td></tr>
<tr><td class="e">Server API</td><td class="v">FPM/FastCGI</td></tr>
<tr><td class="e">Document Root</td><td class="v">/var/www/example.com/public</td></tr>
<tr><td class="e">Loaded Configuration File</td><td class="v">/etc/php/php.ini</td></tr>
</table>
<h2>PHP Extension</h2>
<table>
<tr><td class="e">openssl</td><td class="v">enabled</td></tr>
<tr><td class="e">pdo_mysql</td><td class="v">enabled</td></tr>
</table>
<p>This output was generated by phpinfo().</p>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  6 => 
  array (
    'id' => 'route-htpasswd',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'htpasswd',
      ),
    ),
    'body' => 'admin:$2y$10${{fake.bcadmin:hex:53}}
deploy:$2y$10${{fake.bcdeploy:hex:53}}
backup:$2y$10${{fake.bcbackup:hex:53}}
webmaster:$2y$10${{fake.bcwebmaster:hex:53}}
jenkins:$2y$10${{fake.bcjenkins:hex:53}}
legacy:{SHA}{{fake.shalegacy:b64:27}}=
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  7 => 
  array (
    'id' => 'route-apache-server-status',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'apache-server-status',
        1 => 'server-status',
        2 => 'server-info',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Apache Status</title></head><body>
<h1>Apache Server Status for status.example.com (via 192.0.2.10)</h1>
<dl>
<dt>Server Version: Apache/{{pick:2.4.58,2.4.52,2.4.41}} (Unix) OpenSSL/3.0</dt>
<dt>Server MPM: event</dt>
<dt>Server Built: Jan  1 2024</dt>
<dt>Current Time: Monday, 01-Jan-2024 00:00:00 UTC</dt>
<dt>Server uptime: {{pick:3 days,11 hours,27 days}}</dt>
<dt>Total accesses: 10423 - Total Traffic: 84.2 MB</dt>
</dl>
<pre>
Srv  Client          VHost                Request
0-0  198.51.100.24   www.example.com      GET / HTTP/1.1
1-0  203.0.113.7     www.example.com      GET /favicon.ico HTTP/1.1
</pre>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  8 => 
  array (
    'id' => 'route-package-json',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'package-json',
      ),
    ),
    'body' => '{
  "name": "@example/{{pick:web-app,dashboard,storefront,admin-ui}}",
  "version": "{{pick:1.4.2,3.0.1,2.11.0,0.9.7}}",
  "private": true,
  "description": "Internal web frontend.",
  "scripts": {
    "build": "vite build",
    "test": "vitest run"
  },
  "dependencies": {
    "react": "^18.2.0",
    "axios": "^1.6.0"
  },
  "devDependencies": {
    "vite": "^5.0.0"
  }
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  9 => 
  array (
    'id' => 'route-npmrc',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'npmrc',
        1 => 'npm-token',
        2 => 'npm-registry',
      ),
      'pid' => 
      array (
        0 => 'npm',
      ),
      'body_word_contains' => 
      array (
        0 => '_authToken=',
      ),
    ),
    'body' => '//registry.npmjs.org/:_authToken=npm_{{fake.npmtok:hex:36}}

@acme:registry=https://npm.pkg.github.com
//npm.pkg.github.com/:_authToken=ghp_{{fake.ghtok:hex:36}}

always-auth=true
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  10 => 
  array (
    'id' => 'route-ssh-private-key',
    'match' => 
    array (
      'body_word_contains' => 
      array (
        0 => 'PRIVATE KEY',
      ),
    ),
    'body' => '-----BEGIN RSA PRIVATE KEY-----
{{fake.pem01:b64:64}}
{{fake.pem02:b64:64}}
{{fake.pem03:b64:64}}
{{fake.pem04:b64:64}}
{{fake.pem05:b64:64}}
{{fake.pem06:b64:64}}
{{fake.pem07:b64:64}}
{{fake.pem08:b64:64}}
{{fake.pem09:b64:64}}
{{fake.pem10:b64:64}}
{{fake.pem11:b64:64}}
{{fake.pem12:b64:64}}
{{fake.pem13:b64:64}}
{{fake.pem14:b64:64}}
{{fake.pem15:b64:64}}
{{fake.pem16:b64:64}}
{{fake.pem17:b64:64}}
{{fake.pem18:b64:64}}
{{fake.pem19:b64:64}}
{{fake.pem20:b64:64}}
{{fake.pem21:b64:64}}
{{fake.pem22:b64:64}}
{{fake.pemZZ:b64:40}}
-----END RSA PRIVATE KEY-----
',
    'headers' => 
    array (
      'Content-Type' => 'application/x-pem-file',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  11 => 
  array (
    'id' => 'route-sql-dump',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'database-backup',
        1 => 'sql-dump',
        2 => 'sql-backup',
        3 => 'mysql-dump',
        4 => 'db-dump',
      ),
    ),
    'body' => '-- MySQL dump 10.13  Distrib 8.0.36
--
-- Host: localhost    Database: {{pick:froxlor,app_prod,cms,billing}}
-- ------------------------------------------------------

DROP TABLE IF EXISTS `panel_admins`;
CREATE TABLE `panel_admins` (
  `adminid` int(11) NOT NULL AUTO_INCREMENT,
  `loginname` varchar(50) NOT NULL DEFAULT \'\',
  `password` varchar(255) NOT NULL DEFAULT \'\',
  `email` varchar(255) NOT NULL DEFAULT \'\',
  PRIMARY KEY (`adminid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `panel_admins` VALUES (1,\'admin\',\'$2y$10${{fake.adminpw:hex:53}}\',\'admin@example.com\');

DROP TABLE IF EXISTS `api_credentials`;
CREATE TABLE `api_credentials` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `secret` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `api_credentials` VALUES (1,\'AWS_ACCESS_KEY_ID\',\'{{persona.cloud.aws.accessKeyId}}\');
INSERT INTO `api_credentials` VALUES (2,\'AWS_SECRET_ACCESS_KEY\',\'{{persona.cloud.aws.secretKey}}\');
INSERT INTO `api_credentials` VALUES (3,\'STRIPE_SECRET_KEY\',\'sk_live_{{fake.stripe:hex:24}}\');
INSERT INTO `api_credentials` VALUES (4,\'SENDGRID_API_KEY\',\'SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}\');
',
    'headers' => 
    array (
      'Content-Type' => 'application/sql',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '--',
    ),
  ),
  12 => 
  array (
    'id' => 'route-weblogic',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'weblogic-login',
        1 => 'weblogic',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Oracle WebLogic Server Administration Console</title></head>
<body>
<h1>Oracle WebLogic Server Administration Console</h1>
<p>WebLogic Server Version: 10.3.6.0</p>
<form action="/console/j_security_check" method="post">
<label>Username</label><input name="j_username" type="text" />
<label>Password</label><input name="j_password" type="password" />
<input type="submit" value="Login" />
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'JSESSIONID',
  ),
  13 => 
  array (
    'id' => 'route-exchange-owa',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'microsoft-exchange-panel',
        1 => 'exchange-admin',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Outlook</title></head>
<body>
<div id="loginArea">
<h1>Exchange Admin Center</h1>
<form action="/owa/auth.owa" method="POST">
<input name="username" type="text" placeholder="domain\\user" />
<input name="password" type="password" />
<input type="submit" value="sign in" />
</form>
</div>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'ASP.NET_SessionId',
  ),
  14 => 
  array (
    'id' => 'route-adminer',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'adminer-panel',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Adminer</title></head>
<body>
<h1>Adminer <span class="version">4.8.1</span></h1>
<form action="" method="post">
<p>System <select name="auth[driver]"><option value="server">MySQL</option></select></p>
<p>Server <input name="auth[server]" value="localhost" /></p>
<p>Username <input name="auth[username]" /></p>
<p>Password <input type="password" name="auth[password]" /></p>
<p>Database <input name="auth[db]" /></p>
<p><input type="submit" value="Login" /></p>
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'PHPSESSID',
  ),
  15 => 
  array (
    'id' => 'route-joomla',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'joomla-panel',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head>
<meta name="generator" content="Joomla! - Open Source Content Management" />
<title>Administration - Login</title>
</head>
<body>
<form action="/administrator/index.php" method="post">
<input name="username" type="text" />
<input name="passwd" type="password" />
<button type="submit">Log in</button>
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'PHPSESSID',
  ),
  16 => 
  array (
    'id' => 'route-wp-readme',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'wordpress-readme-file',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>WordPress &#8250; ReadMe</title></head>
<body>
<h1 id="logo">WordPress</h1>
<p>Version {{pick:6.4.2,6.3.1,5.9.3,6.2.2}}</p>
<h2>Installation</h2>
<p>Famous 5-minute install.</p>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=UTF-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  17 => 
  array (
    'id' => 'route-citrix',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'citrix-adc-gateway-panel',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>Citrix Gateway</title></head>
<body>
<div class="CTXMSAM_LogonFont">Citrix Gateway</div>
<script type="text/javascript">var _ctxstxt_CitrixCopyright = "Citrix Systems, Inc. All rights reserved.";</script>
<form method="post" action="/cgi/login">
<input name="login" type="text" />
<input name="passwd" type="password" />
<input type="submit" value="Log On" />
</form>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'NSC_AAAC',
  ),
  18 => 
  array (
    'id' => 'route-directory-listing',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'directory-listing',
      ),
    ),
    'body' => '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html><head><title>Index of /backup</title></head>
<body>
<h1>Index of /backup</h1>
<pre><a href="?C=N;O=D">Name</a>  <a href="?C=M;O=A">Last modified</a>  <a href="?C=S;O=A">Size</a>
<hr>
<a href="../">Parent Directory</a>                       -
<a href="database.sql">database.sql</a>      2024-01-01 12:00  4.2M
<a href="config.php.bak">config.php.bak</a>  2024-01-01 12:00  2.1K
<a href="www.tar.gz">www.tar.gz</a>          2024-01-01 12:00   18M
<hr></pre>
<address>Apache Server at localhost Port 80</address>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  19 => 
  array (
    'id' => 'route-django-admin',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'django-admin-panel',
        1 => 'default-django-page',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html lang="en"><head><title>Log in | Django site admin</title></head>
<body class="login">
<div id="container">
<div id="header"><h1 id="site-name">Django administration</h1></div>
<div id="content">
<form action="/admin/login/" method="post" id="login-form">
<div class="form-row"><label>Username:</label><input type="text" name="username" /></div>
<div class="form-row"><label>Password:</label><input type="password" name="password" /></div>
<div class="submit-row"><input type="submit" value="Log in" /></div>
</form>
</div>
</div>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'sessionid',
  ),
  20 => 
  array (
    'id' => 'route-tomcat-manager',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'apache-tomcat-exposed',
        1 => 'tomcat-default-login',
        2 => 'tomcat',
      ),
    ),
    'body' => '<!DOCTYPE html>
<html><head><title>/manager</title></head>
<body>
<h1>Tomcat Web Application Manager</h1>
<table>
<tr><th>Path</th><th>Version</th><th>Display Name</th><th>Running</th><th>Sessions</th></tr>
<tr><td>/</td><td>None</td><td>Welcome to Tomcat</td><td>true</td><td>0</td></tr>
<tr><td>/manager</td><td>None</td><td>Tomcat Manager Application</td><td>true</td><td>1</td></tr>
</table>
<h2>Server Information</h2>
<table>
<tr><th>Tomcat Version</th><th>JVM Version</th><th>OS Name</th></tr>
<tr><td>Apache Tomcat/{{pick:9.0.71,8.5.87,10.1.7}}</td><td>17.0.6+10</td><td>Linux</td></tr>
</table>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html;charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'JSESSIONID',
  ),
  21 => 
  array (
    'id' => 'route-basic-auth',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-basic-auth',
      ),
    ),
    'body' => '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head><title>401 Authorization Required</title></head>
<body><h1>Authorization Required</h1>
<p>This server could not verify that you are authorized to access the document requested.</p>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=iso-8859-1',
      'WWW-Authenticate' => 'Basic realm="Restricted Area"',
    ),
  ),
  22 => 
  array (
    'id' => 'route-credentials-txt',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-credentials-txt',
      ),
    ),
    'body' => '# production credentials — rotate quarterly

# AWS — STS
AWS_ACCESS_KEY_ID={{persona.cloud.aws.accessKeyId}}
AWS_SECRET_ACCESS_KEY={{persona.cloud.aws.secretKey}}
AWS_SESSION_TOKEN=FQoGZXIvYXdz{{fake.awssess1:b64:43}}{{fake.awssess2:b64:43}}{{fake.awssess3:b64:43}}
AWS_DEFAULT_REGION=eu-west-1

# DigitalOcean
DIGITALOCEAN_TOKEN=dop_v1_{{fake.do:hex:64}}

# Cloudflare
CLOUDFLARE_API_TOKEN={{fake.cf:hex:40}}

# Stripe — billing
STRIPE_SECRET_KEY=sk_live_{{fake.ssk:hex:24}}

# SendGrid — mail
SENDGRID_API_KEY=SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}

# GitHub
GITHUB_TOKEN=ghp_{{fake.gh:hex:36}}

# Postgres
DATABASE_URL=postgres://app_prod:{{fake.pg:hex:20}}@db-{{fake.pgh:hex:6}}.eu-west-1.rds.amazonaws.com:5432/app_production

# Slack
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/T{{fake.slt:hex:8}}/B{{fake.slb:hex:8}}/{{fake.sltok:hex:24}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  23 => 
  array (
    'id' => 'route-terraform-tfstate',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-terraform-tfstate',
      ),
    ),
    'body' => '{
  "version": 4,
  "terraform_version": "1.6.2",
  "serial": 42,
  "resources": [
    {
      "type": "aws_iam_access_key",
      "name": "deploy",
      "provider": "provider[\\"registry.terraform.io/hashicorp/aws\\"]",
      "instances": [
        { "attributes": {
          "id": "{{persona.cloud.aws.accessKeyId}}",
          "secret": "{{persona.cloud.aws.secretKey}}",
          "user": "ci-deploy",
          "status": "Active"
        } }
      ]
    },
    {
      "type": "aws_db_instance",
      "name": "primary",
      "provider": "provider[\\"registry.terraform.io/hashicorp/aws\\"]",
      "instances": [
        { "attributes": {
          "identifier": "app-prod",
          "engine": "postgres",
          "instance_class": "db.r5.large",
          "allocated_storage": 200,
          "address": "db-{{fake.tfdbhost:hex:6}}.cluster-cg{{fake.tfdbacct:hex:9}}.eu-west-1.rds.amazonaws.com",
          "endpoint": "db-{{fake.tfdbhost:hex:6}}.cluster-cg{{fake.tfdbacct:hex:9}}.eu-west-1.rds.amazonaws.com:5432",
          "port": 5432,
          "username": "app_prod",
          "password": "{{fake.tfdbpass:hex:24}}"
        } }
      ]
    },
    {
      "type": "random_password",
      "name": "app_secret",
      "provider": "provider[\\"registry.terraform.io/hashicorp/random\\"]",
      "instances": [
        { "attributes": {
          "id": "none",
          "length": 32,
          "special": false,
          "result": "{{fake.tfrandpass:hex:32}}"
        } }
      ]
    }
  ]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  24 => 
  array (
    'id' => 'route-users-csv',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-users-csv',
      ),
    ),
    'body' => 'id,username,email,password_hash,role
1,admin,admin@example.com,$2y$10${{fake.u1:hex:53}},superadmin
2,jdoe,jane.doe@example.com,$2y$10${{fake.u2:hex:53}},admin
3,bsmith,bob.smith@example.com,$2y$10${{fake.u3:hex:53}},editor
4,mwilson,mike.wilson@example.com,$2y$10${{fake.u4:hex:53}},user
5,svcapi,api@example.com,$2y$10${{fake.u5:hex:53}},api
6,helpdesk,support@example.com,$2y$10${{fake.u6:hex:53}},support
7,financeops,finance@example.com,$2y$10${{fake.u7:hex:53}},finance
8,rpatel,raj.patel@example.com,$2y$10${{fake.u8:hex:53}},user
',
    'headers' => 
    array (
      'Content-Type' => 'text/csv; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  25 => 
  array (
    'id' => 'route-sql-backup',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-sql-backup',
      ),
    ),
    'body' => '-- MySQL dump 10.13  Distrib 8.0.36
-- Host: localhost    Database: {{pick:app_prod,cms,billing,shop}}
-- ------------------------------------------------------

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `users` VALUES (1,\'admin@example.com\',\'$2y$10${{fake.bc1:hex:53}}\');
INSERT INTO `users` VALUES (2,\'j.harper@example.com\',\'$2y$10${{fake.bc2:hex:53}}\');
INSERT INTO `users` VALUES (3,\'s.ncube@example.com\',\'$2y$10${{fake.bc3:hex:53}}\');
INSERT INTO `users` VALUES (4,\'m.delacroix@example.com\',\'$2y$10${{fake.bc4:hex:53}}\');
INSERT INTO `users` VALUES (5,\'support@example.com\',\'$2y$10${{fake.bc5:hex:53}}\');

DROP TABLE IF EXISTS `api_keys`;
CREATE TABLE `api_keys` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(64) NOT NULL,
  `secret` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `api_keys` VALUES (1,\'AWS_ACCESS_KEY_ID\',\'{{persona.cloud.aws.accessKeyId}}\');
INSERT INTO `api_keys` VALUES (2,\'AWS_SECRET_ACCESS_KEY\',\'{{persona.cloud.aws.secretKey}}\');
INSERT INTO `api_keys` VALUES (3,\'STRIPE_SECRET\',\'sk_live_{{fake.stripesk:hex:24}}\');
INSERT INTO `api_keys` VALUES (4,\'SENDGRID_API_KEY\',\'SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}\');
',
    'headers' => 
    array (
      'Content-Type' => 'application/sql',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '--',
    ),
  ),
  26 => 
  array (
    'id' => 'route-phpmyadmin',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-phpmyadmin',
      ),
    ),
    'body' => '<!DOCTYPE HTML>
<html lang="en"><head><title>phpMyAdmin</title>
<link rel="stylesheet" type="text/css" href="phpmyadmin.css.php" />
</head>
<body class="loginform">
<div class="container">
<h1>Welcome to phpMyAdmin</h1>
<form method="post" action="index.php" name="login_form" class="login">
<fieldset>
<legend>Log in</legend>
<label for="input_username">Username:</label>
<input type="text" name="pma_username" id="input_username" value="root" />
<label for="input_password">Password:</label>
<input type="password" name="pma_password" id="input_password" />
</fieldset>
<input type="submit" value="Go" id="input_go" />
</form>
<div class="footer">phpMyAdmin {{pick:5.2.1,5.1.3,4.9.7}}</div>
</div>
</body></html>
',
    'headers' => 
    array (
      'Content-Type' => 'text/html; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
    'set_cookie' => 'phpMyAdmin',
  ),
  27 => 
  array (
    'id' => 'route-ai-claude-json',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-claude-json',
      ),
    ),
    'body' => '{
"numStartups": 42,
"autoUpdaterStatus": "enabled",
"model": "claude-sonnet-4-20250514",
"apiKey": "{{persona.cloud.anthropic.apiKey}}",
"mcpServers": {
  "filesystem": {
    "command": "npx",
    "args": ["-y", "@modelcontextprotocol/server-filesystem", "/srv/app"]
  },
  "github": {
    "command": "npx",
    "args": ["-y", "@modelcontextprotocol/server-github"],
    "env": { "GITHUB_PERSONAL_ACCESS_TOKEN": "ghp_{{fake.gh:hex:36}}" }
  }
}
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  28 => 
  array (
    'id' => 'route-ai-claude-settings',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'claude-settings-exposure',
      ),
    ),
    'body' => '{
"env": {
  "ANTHROPIC_API_KEY": "{{persona.cloud.anthropic.apiKey}}",
  "ANTHROPIC_MODEL": "claude-sonnet-4-20250514"
},
"permissions": {
  "allow": ["Bash(git*)", "Read", "Edit", "WebFetch"],
  "deny": ["Bash(rm*)"]
},
"model": "claude-sonnet-4-20250514",
"cleanupPeriodDays": 30
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  29 => 
  array (
    'id' => 'route-ai-claude-desktop',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-claude-desktop',
      ),
    ),
    'body' => '{
"mcpServers": {
  "filesystem": {
    "command": "npx",
    "args": ["-y", "@modelcontextprotocol/server-filesystem", "/Users/dev/Documents"]
  },
  "github": {
    "command": "npx",
    "args": ["-y", "@modelcontextprotocol/server-github"],
    "env": { "GITHUB_PERSONAL_ACCESS_TOKEN": "ghp_{{fake.gh:hex:36}}" }
  }
}
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  30 => 
  array (
    'id' => 'route-ai-mcp-json',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-mcp-json',
      ),
    ),
    'body' => '{
"mcpServers": {
  "anthropic": {
    "command": "npx",
    "args": ["-y", "@anthropic-ai/mcp-server"],
    "env": { "ANTHROPIC_API_KEY": "{{persona.cloud.anthropic.apiKey}}" }
  },
  "filesystem": {
    "command": "npx",
    "args": ["-y", "@modelcontextprotocol/server-filesystem", "/srv/app"]
  }
}
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  31 => 
  array (
    'id' => 'route-ai-continue',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-continue',
      ),
    ),
    'body' => '{
"models": [
  {
    "title": "Claude Sonnet 4",
    "provider": "anthropic",
    "model": "claude-sonnet-4-20250514",
    "apiKey": "{{persona.cloud.anthropic.apiKey}}"
  },
  {
    "title": "GPT-4o",
    "provider": "openai",
    "model": "gpt-4o",
    "apiKey": "{{persona.cloud.openai.apiKey}}"
  }
]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  32 => 
  array (
    'id' => 'route-ai-aider',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-aider',
      ),
    ),
    'body' => '## aider configuration
openai-api-key: {{persona.cloud.openai.apiKey}}
anthropic-api-key: {{persona.cloud.anthropic.apiKey}}
model: sonnet
weak-model: gpt-4o-mini
auto-commits: true
gitignore: false
',
    'headers' => 
    array (
      'Content-Type' => 'text/yaml; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  33 => 
  array (
    'id' => 'route-ai-copilot-token',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-copilot-token',
      ),
    ),
    'body' => '{
"token": "{{persona.cloud.github.copilotToken}}",
"expires_at": 1756605600,
"refresh_in": 1500,
"annotations_enabled": true,
"chat_enabled": true
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  34 => 
  array (
    'id' => 'route-ai-openai-models',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-ai-openai-models',
      ),
    ),
    'body' => '{
"object":"list",
"data":[
{"id":"gpt-4o","object":"model","created":1715367049,"owned_by":"openai"},
{"id":"gpt-4o-mini","object":"model","created":1721260800,"owned_by":"openai"},
{"id":"gpt-4-turbo","object":"model","created":1712620800,"owned_by":"openai"},
{"id":"text-embedding-3-large","object":"model","created":1705363200,"owned_by":"openai"}
]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  35 => 
  array (
    'id' => 'route-mcp-endpoint',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-mcp-endpoint',
      ),
    ),
    'body' => '{"jsonrpc":"2.0","error":{"code":-32000,"message":"Missing session ID"},"id":null}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
  ),
  36 => 
  array (
    'id' => 'route-llm-auth',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-llm-auth',
      ),
    ),
    'body' => '{"error":{"message":"You didn\'t provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY).","type":"invalid_request_error","param":null,"code":null}}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
  ),
  37 => 
  array (
    'id' => 'route-v1-models-enrich',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'xinference',
        1 => 'jan-detect',
      ),
    ),
    'body' => '{
"object":"list",
"data":[
{"id":"gpt-4o","object":"model","created":1715367049,"owned_by":"openai"},
{"id":"gpt-4o-mini","object":"model","created":1721260800,"owned_by":"openai"},
{"id":"text-embedding-3-large","object":"model","created":1705363200,"owned_by":"openai"}
]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  38 => 
  array (
    'id' => 'route-v1-models-vllm',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'vllm-openai-api-exposed',
      ),
    ),
    'body' => '{
"object" : "list",
"data" : [
{"id" : "meta-llama/Meta-Llama-3.1-8B-Instruct", "object" : "model", "created" : 1715367049, "owned_by" : "vllm", "root" : "meta-llama/Meta-Llama-3.1-8B-Instruct", "parent" : null, "max_model_len" : 131072, "permission" : []},
{"id" : "mistralai/Mistral-7B-Instruct-v0.3", "object" : "model", "created" : 1716163200, "owned_by" : "vllm", "root" : "mistralai/Mistral-7B-Instruct-v0.3", "parent" : null, "max_model_len" : 32768, "permission" : []}
]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  39 => 
  array (
    'id' => 'route-config-php',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-config-php',
      ),
    ),
    'body' => '<?php
// Application configuration — production.

define(\'DB_HOST\', \'{{persona.db.host}}\');
define(\'DB_NAME\', \'{{persona.db.name}}\');
define(\'DB_USER\', \'{{persona.db.user}}\');
define(\'DB_PASSWORD\', \'{{persona.db.password}}\');

define(\'STRIPE_SECRET_KEY\', \'{{persona.cloud.stripe.secretKey}}\');
define(\'SENDGRID_API_KEY\', \'{{persona.cloud.sendgrid.apiKey}}\');
define(\'JWT_SECRET\', \'{{persona.secret.jwt}}\');

define(\'AWS_ACCESS_KEY_ID\', \'{{persona.cloud.aws.accessKeyId}}\');
define(\'AWS_SECRET_ACCESS_KEY\', \'{{persona.cloud.aws.secretKey}}\');
define(\'AWS_DEFAULT_REGION\', \'{{persona.cloud.aws.region}}\');
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  40 => 
  array (
    'id' => 'route-envfile-prod',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-envfile-prod',
      ),
    ),
    'body' => 'APP_ENV=production
APP_DEBUG=false

DB_CONNECTION=pgsql
DB_HOST={{persona.db.host}}
DB_PORT=5432
DB_DATABASE={{persona.db.name}}
DB_USERNAME={{persona.db.user}}
DB_PASSWORD={{persona.db.password}}

AWS_ACCESS_KEY_ID={{persona.cloud.aws.accessKeyId}}
AWS_SECRET_ACCESS_KEY={{persona.cloud.aws.secretKey}}
AWS_DEFAULT_REGION={{persona.cloud.aws.region}}

STRIPE_SECRET_KEY={{persona.cloud.stripe.secretKey}}
SENDGRID_API_KEY={{persona.cloud.sendgrid.apiKey}}
JWT_SECRET={{persona.secret.jwt}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  41 => 
  array (
    'id' => 'route-secrets-json',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-secrets-json',
      ),
    ),
    'body' => '{
"db": {
  "host": "{{persona.db.host}}",
  "name": "{{persona.db.name}}",
  "user": "{{persona.db.user}}",
  "password": "{{persona.db.password}}"
},
"aws": {
  "accessKeyId": "{{persona.cloud.aws.accessKeyId}}",
  "secretKey": "{{persona.cloud.aws.secretKey}}",
  "region": "{{persona.cloud.aws.region}}"
},
"stripe": { "secretKey": "{{persona.cloud.stripe.secretKey}}" },
"sendgrid": { "apiKey": "{{persona.cloud.sendgrid.apiKey}}" },
"jwt": { "secret": "{{persona.secret.jwt}}" }
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  42 => 
  array (
    'id' => 'route-docker-compose',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-docker-compose',
      ),
    ),
    'body' => 'version: "3.8"
services:
  app:
    image: registry.example.com/app:latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://{{persona.db.user}}:{{persona.db.password}}@db:5432/{{persona.db.name}}
      AWS_ACCESS_KEY_ID: {{persona.cloud.aws.accessKeyId}}
      AWS_SECRET_ACCESS_KEY: {{persona.cloud.aws.secretKey}}
      STRIPE_SECRET_KEY: {{persona.cloud.stripe.secretKey}}
      SENDGRID_API_KEY: {{persona.cloud.sendgrid.apiKey}}
      JWT_SECRET: {{persona.secret.jwt}}
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: {{persona.db.user}}
      POSTGRES_PASSWORD: {{persona.db.password}}
      POSTGRES_DB: {{persona.db.name}}
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    ports:
      - "587:587"
',
    'headers' => 
    array (
      'Content-Type' => 'text/yaml; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  43 => 
  array (
    'id' => 'route-application-properties',
    'match' => 
    array (
      'pid' => 
      array (
        0 => 'route-application-properties',
      ),
    ),
    'body' => 'spring.datasource.url=jdbc:postgresql://{{persona.db.host}}:5432/{{persona.db.name}}
spring.datasource.username={{persona.db.user}}
spring.datasource.password={{persona.db.password}}

stripe.secret-key={{persona.cloud.stripe.secretKey}}
sendgrid.api-key={{persona.cloud.sendgrid.apiKey}}
jwt.secret={{persona.secret.jwt}}

cloud.aws.credentials.access-key={{persona.cloud.aws.accessKeyId}}
cloud.aws.credentials.secret-key={{persona.cloud.aws.secretKey}}
cloud.aws.region.static={{persona.cloud.aws.region}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/plain; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  44 => 
  array (
    'id' => 'route-application-yml',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'application-yaml',
      ),
    ),
    'body' => 'runtime: java
spring:
  datasource:
    url: jdbc:postgresql://{{persona.db.host}}:5432/{{persona.db.name}}
    username: {{persona.db.user}}
    password: {{persona.db.password}}
stripe:
  secret-key: {{persona.cloud.stripe.secretKey}}
sendgrid:
  api-key: {{persona.cloud.sendgrid.apiKey}}
jwt:
  secret: {{persona.secret.jwt}}
cloud:
  aws:
    access-key: {{persona.cloud.aws.accessKeyId}}
    secret-key: {{persona.cloud.aws.secretKey}}
    region: {{persona.cloud.aws.region}}
',
    'headers' => 
    array (
      'Content-Type' => 'text/yaml; charset=utf-8',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '#',
    ),
  ),
  45 => 
  array (
    'id' => 'route-settings-json',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'vscode-settings',
      ),
    ),
    'body' => '{
"version": "0.2.0",
"configurations": [
{
"name": "Launch app",
"type": "node",
"request": "launch",
"program": "/srv/app/server.js",
"env": {
"ANTHROPIC_API_KEY": "{{persona.cloud.anthropic.apiKey}}",
"DATABASE_URL": "postgres://{{persona.db.user}}:{{persona.db.password}}@{{persona.db.host}}:5432/{{persona.db.name}}"
}
}
]
}
',
    'headers' => 
    array (
      'Content-Type' => 'application/json',
    ),
    'taunt' => 
    array (
      'mode' => 'inline_field',
      'key' => '_comment',
    ),
  ),
  46 => 
  array (
    'id' => 'route-web-config',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'web-config',
      ),
    ),
    'body' => '<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <connectionStrings>
    <add name="DefaultConnection" connectionString="Server={{persona.db.host}};Database={{persona.db.name}};User Id={{persona.db.user}};Password={{persona.db.password}};" providerName="System.Data.SqlClient" />
  </connectionStrings>
  <appSettings>
    <add key="Stripe:SecretKey" value="{{persona.cloud.stripe.secretKey}}" />
    <add key="SendGrid:ApiKey" value="{{persona.cloud.sendgrid.apiKey}}" />
    <add key="Jwt:Secret" value="{{persona.secret.jwt}}" />
    <add key="AWS:AccessKeyId" value="{{persona.cloud.aws.accessKeyId}}" />
    <add key="AWS:SecretAccessKey" value="{{persona.cloud.aws.secretKey}}" />
  </appSettings>
  <system.webServer>
    <security>
      <requestFiltering>
        <hiddenSegments>
          <add segment="bin" />
        </hiddenSegments>
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
',
    'headers' => 
    array (
      'Content-Type' => 'application/xml',
    ),
    'taunt' => 
    array (
      'mode' => 'block',
      'open' => '<!--',
      'close' => '-->',
    ),
  ),
  47 => 
  array (
    'id' => 'route-config-js-firebase',
    'match' => 
    array (
      'template_needle' => 
      array (
        0 => 'firebase-config-exposure',
      ),
    ),
    'body' => '// Firebase web app configuration
const firebaseConfig = {
  apiKey: "{{persona.cloud.google.apiKey}}",
  authDomain: "{{persona.company.slug}}.firebaseapp.com",
  databaseURL: "https://{{persona.company.slug}}.firebaseio.com",
  projectId: "{{persona.company.slug}}",
  storageBucket: "{{persona.company.slug}}.appspot.com",
  messagingSenderId: "{{fake.fbsender:hex:12}}",
  appId: "1:{{fake.fbappnum:hex:12}}:web:{{fake.fbappid:hex:16}}"
};
firebase.initializeApp(firebaseConfig);
',
    'headers' => 
    array (
      'Content-Type' => 'application/javascript',
    ),
    'taunt' => 
    array (
      'mode' => 'line',
      'open' => '//',
    ),
  ),
);
