<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-params` — DO NOT EDIT.
// Provenance: source-tree sha256=f34065fa68b0ddc6e2584c4465e246a55727be158629ec1e39d66bb0aacc76ea schema=1

return array (
  'schema' => 1,
  'buckets' => 
  array (
    '@fs' => 
    array (
      0 => 
      array (
        'id' => 'param-vite-fs',
        'severity' => 'high',
        'tags' => 
        array (
          0 => 'param',
          1 => 'vite',
          2 => 'lfi',
        ),
        'status' => 404,
        'method' => 'GET',
        'regex' => '^/@fs/(?P<path>.+)$',
        'captures' => 
        array (
          0 => 'path',
        ),
        'response' => 
        array (
          'headers' => 
          array (
            'Content-Type' => 'text/plain; charset=utf-8',
          ),
          'body' => 'Not Found: /@fs/{{match.path}}
',
        ),
        'reflects_input' => true,
        'reflect_class' => 'fs-read',
        'behavior' => 'traversal-read',
        'traversal-read' => 
        array (
          'allow' => 
          array (
            0 => 
            array (
              'suffix' => '.env',
              'content' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/plain; charset=utf-8',
                ),
                'body' => 'APP_NAME={{persona.company.name}}
APP_ENV=production
APP_KEY=base64:{{fake.app_key:b64:44}}
APP_DEBUG=false
APP_URL=https://{{persona.company.domain}}

LOG_CHANNEL=stack

DB_CONNECTION=pgsql
DB_HOST=db-{{fake.pghost:hex:12}}.cluster-cg{{fake.pgacct:hex:9}}.{{persona.cloud.aws.region}}.rds.amazonaws.com
DB_PORT=5432
DB_DATABASE={{persona.db.name}}
DB_USERNAME={{persona.db.user}}
DB_PASSWORD={{persona.db.password}}

REDIS_HOST=cache-{{fake.redishost:hex:12}}.0001.{{persona.cloud.aws.regionCode}}.cache.amazonaws.com
REDIS_PORT=6379
REDIS_PASSWORD={{fake.redispass:hex:32}}

# AWS — S3 uploads + SES
AWS_ACCESS_KEY_ID={{persona.cloud.aws.accessKeyId}}
AWS_SECRET_ACCESS_KEY={{persona.cloud.aws.secretKey}}
AWS_DEFAULT_REGION={{persona.cloud.aws.region}}
AWS_BUCKET={{persona.company.slug}}-prod-uploads

# Stripe — billing
STRIPE_KEY=pk_live_{{fake.stripe_pk:hex:24}}
STRIPE_SECRET=sk_live_{{fake.stripe_sk:hex:24}}
STRIPE_WEBHOOK_SECRET=whsec_{{fake.stripe_whsec:hex:32}}

# Mail — SendGrid
MAIL_MAILER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=apikey
SENDGRID_API_KEY=SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}

JWT_SECRET={{fake.jwtsecret:hex:64}}
SLACK_WEBHOOK_URL=https://hooks.slack.com/services/T{{fake.slackt:hex:8}}/B{{fake.slackb:hex:8}}/{{fake.slacktok:hex:24}}
',
                'status' => 200,
              ),
            ),
            1 => 
            array (
              'suffix' => '.aws/credentials',
              'content' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/plain; charset=utf-8',
                ),
                'body' => '[default]
aws_access_key_id = {{persona.cloud.aws.accessKeyId}}
aws_secret_access_key = {{persona.cloud.aws.secretKey}}
region = {{persona.cloud.aws.region}}
',
                'status' => 200,
              ),
            ),
            2 => 
            array (
              'basename' => 'wp-config.php',
              'content' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/plain; charset=utf-8',
                ),
                'body' => '<?php
/**
 * The base configuration for WordPress (backup copy).
 */

// ** Database settings ** //
define(\'DB_NAME\', \'{{persona.db.wpName}}\');
define(\'DB_USER\', \'{{persona.db.user}}\');
define(\'DB_PASSWORD\', \'{{fake.dbpass:hex:24}}\');
define(\'DB_HOST\', \'wp-prod-db-{{fake.dbhost:hex:12}}.cluster-cg{{fake.dbacct:hex:9}}.{{persona.cloud.aws.region}}.rds.amazonaws.com\');
define(\'DB_CHARSET\', \'utf8mb4\');
define(\'DB_COLLATE\', \'\');

// ** WP Offload Media (Amazon S3) bucket credentials ** //
define(\'AS3CF_SETTINGS\', serialize(array(
    \'provider\'          => \'aws\',
    \'access-key-id\'     => \'{{persona.cloud.aws.accessKeyId}}\',
    \'secret-access-key\' => \'{{persona.cloud.aws.secretKey}}\',
    \'bucket\'            => \'media.{{persona.company.domain}}\',
    \'region\'            => \'{{persona.cloud.aws.region}}\',
)));

// ** WooCommerce Stripe Gateway ** //
define(\'WC_STRIPE_SECRET_KEY\', \'sk_live_{{fake.wcsk:hex:24}}\');

// ** SendGrid (WP Mail SMTP) ** //
define(\'SENDGRID_API_KEY\', \'SG.{{fake.sg1:hex:22}}.{{fake.sg2:hex:43}}\');

// ** Authentication unique keys and salts ** //
define(\'AUTH_KEY\', \'{{fake.authkey:hex:64}}\');
define(\'AUTH_SALT\', \'{{fake.authsalt:hex:64}}\');

$table_prefix = \'wp_\';
define(\'WP_DEBUG\', false);
',
                'status' => 200,
              ),
            ),
            3 => 
            array (
              'suffix' => 'proc/self/environ',
              'content' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/plain; charset=utf-8',
                ),
                'body' => '{{canned.environ}}',
                'status' => 200,
              ),
            ),
            4 => 
            array (
              'suffix' => 'etc/passwd',
              'content' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/plain; charset=utf-8',
                ),
                'body' => '{{canned.passwd}}',
                'status' => 200,
              ),
            ),
            5 => 
            array (
              'suffix' => 'var/run/secrets/kubernetes.io/serviceaccount/token',
              'content' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/plain; charset=utf-8',
                ),
                'body' => '{{canned.k8s_sa_unsigned}}.{{fake.k8s_sig:b64url:43}}{{fake.k8s_sig2:b64url:43}}',
                'status' => 200,
              ),
            ),
          ),
        ),
      ),
    ),
    'catalog' => 
    array (
      0 => 
      array (
        'id' => 'param-sqli-differential',
        'severity' => 'high',
        'tags' => 
        array (
          0 => 'param',
          1 => 'sqli',
          2 => 'behavioral',
        ),
        'status' => 200,
        'method' => 'GET',
        'regex' => '^/catalog/(?P<slug>[^/]+)$',
        'captures' => 
        array (
          0 => 'slug',
        ),
        'response' => 
        array (
          'headers' => 
          array (
            'Content-Type' => 'text/html; charset=utf-8',
          ),
          'body' => '<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>{{persona.company.name}} — Product catalog</title></head>
<body>
<h1>Product catalog</h1>
<p>Showing in-stock products for {{persona.company.name}}.</p>
<table>
<tr><th>SKU</th><th>Product</th><th>Seller</th><th>Availability</th></tr>
<tr><td>SKU-{{fake.sku1:hex:8}}</td><td>{{pick:Wireless Keyboard,USB-C Charger,Laptop Stand,Desk Lamp,Webcam 1080p}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
<tr><td>SKU-{{fake.sku2:hex:8}}</td><td>{{pick:Mechanical Mouse,HDMI Cable,Monitor Arm,Cable Organizer,Bluetooth Speaker}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
<tr><td>SKU-{{fake.sku3:hex:8}}</td><td>{{pick:Noise Headset,Portable SSD,Phone Mount,Laptop Sleeve,Ring Light}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
</table>
<p>3 products in this category.</p>
</body>
</html>
',
        ),
        'behavior' => 'branch',
        'branch' => 
        array (
          'cases' => 
          array (
            0 => 
            array (
              'when' => 
              array (
                'in' => 'request',
                'regex' => '\'\'|\\\\\\\\|[-+]\\s*0\\b|\\b(?:and|or)\\s+\'?(\\w+)\'?\\s*=\\s*\'?\\1\\b',
              ),
              'response' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/html; charset=utf-8',
                ),
                'body' => '<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>{{persona.company.name}} — Product catalog</title></head>
<body>
<h1>Product catalog</h1>
<p>Showing in-stock products for {{persona.company.name}}.</p>
<table>
<tr><th>SKU</th><th>Product</th><th>Seller</th><th>Availability</th></tr>
<tr><td>SKU-{{fake.sku1:hex:8}}</td><td>{{pick:Wireless Keyboard,USB-C Charger,Laptop Stand,Desk Lamp,Webcam 1080p}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
<tr><td>SKU-{{fake.sku2:hex:8}}</td><td>{{pick:Mechanical Mouse,HDMI Cable,Monitor Arm,Cable Organizer,Bluetooth Speaker}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
<tr><td>SKU-{{fake.sku3:hex:8}}</td><td>{{pick:Noise Headset,Portable SSD,Phone Mount,Laptop Sleeve,Ring Light}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
</table>
<p>3 products in this category.</p>
</body>
</html>
',
              ),
            ),
            1 => 
            array (
              'when' => 
              array (
                'in' => 'request',
                'regex' => '\\b(?:and|or)\\s+\'?\\w+\'?\\s*=\\s*\'?\\w+|=\\s*\\d+\\s*-\\s*[1-9]',
              ),
              'response' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/html; charset=utf-8',
                ),
                'body' => '<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>{{persona.company.name}} — Product catalog</title></head>
<body>
<h1>Product catalog</h1>
<p>No products found in this category.</p>
</body>
</html>
',
              ),
            ),
            2 => 
            array (
              'when' => 
              array (
                'in' => 'request',
                'regex' => '\\w[\'\\\\](?=\\s|$)',
              ),
              'response' => 
              array (
                'headers' => 
                array (
                  'Content-Type' => 'text/html; charset=utf-8',
                ),
                'body' => '{{attack.sqli.prefix}}You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'{{attack.sqli.near}}\' at line 1{{attack.sqli.suffix}}
',
                'status' => 500,
              ),
            ),
          ),
          'default' => 
          array (
            'response' => 
            array (
              'headers' => 
              array (
                'Content-Type' => 'text/html; charset=utf-8',
              ),
              'body' => '<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>{{persona.company.name}} — Product catalog</title></head>
<body>
<h1>Product catalog</h1>
<p>Showing in-stock products for {{persona.company.name}}.</p>
<table>
<tr><th>SKU</th><th>Product</th><th>Seller</th><th>Availability</th></tr>
<tr><td>SKU-{{fake.sku1:hex:8}}</td><td>{{pick:Wireless Keyboard,USB-C Charger,Laptop Stand,Desk Lamp,Webcam 1080p}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
<tr><td>SKU-{{fake.sku2:hex:8}}</td><td>{{pick:Mechanical Mouse,HDMI Cable,Monitor Arm,Cable Organizer,Bluetooth Speaker}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
<tr><td>SKU-{{fake.sku3:hex:8}}</td><td>{{pick:Noise Headset,Portable SSD,Phone Mount,Laptop Sleeve,Ring Light}}</td><td>{{fake.person.full}}</td><td>In stock</td></tr>
</table>
<p>3 products in this category.</p>
</body>
</html>
',
            ),
          ),
        ),
      ),
    ),
  ),
);
