<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-routes` — DO NOT EDIT.

return array (
  'templates' => 
  array (
    'route-basic-auth' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'basic-auth',
        1 => '401',
        2 => 'exposure',
      ),
      'name' => 'Basic Auth challenge',
    ),
    'route-credentials-txt' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'credentials',
        2 => 'secrets',
      ),
      'name' => 'Exposed credentials.txt',
    ),
    'route-terraform-tfstate' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'terraform',
        2 => 'secrets',
      ),
      'name' => 'Exposed terraform.tfstate',
    ),
    'route-users-csv' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'pii',
        2 => 'credentials',
      ),
      'name' => 'Exposed users.csv',
    ),
    'route-sql-backup' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'database',
        2 => 'backup',
      ),
      'name' => 'Exposed SQL backup',
    ),
    'route-phpmyadmin' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'panel',
        2 => 'exposure',
      ),
      'name' => 'phpMyAdmin login',
    ),
  ),
  'routes' => 
  array (
    'GET /private/' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'Authorization Required',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-basic-auth',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-basic-auth',
        ),
        'th' => 
        array (
          'WWW-Authenticate' => 
          array (
            0 => 'Basic realm=',
          ),
        ),
      ),
    ),
    'GET /credentials.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /creds.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /backup/credentials.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /.terraform/terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /infra/terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /export/users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /backup/users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /backup.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /database.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /dump.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /db_backup.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /phpmyadmin/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpMyAdmin/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /pma/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpmyadmin/index.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
  ),
);
