<?php

declare(strict_types=1);

// GENERATED by `funnypot compile-routes` — DO NOT EDIT.

return array (
  'templates' => 
  array (
    'route-ai-ollama-ps' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'ai-recon',
        1 => 'exposure',
        2 => 'appliance',
      ),
      'name' => 'Exposed Ollama running models',
    ),
    'route-ai-ollama-tags' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'ai-recon',
        1 => 'exposure',
        2 => 'appliance',
      ),
      'name' => 'Exposed Ollama model list',
    ),
    'route-basic-auth' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'basic-auth',
        1 => '401',
        2 => 'exposure',
      ),
      'name' => 'Basic Auth challenge',
    ),
    'route-credentials-txt' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'credentials',
        2 => 'secrets',
      ),
      'name' => 'Exposed credentials.txt',
    ),
    'route-terraform-tfstate' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'terraform',
        2 => 'secrets',
      ),
      'name' => 'Exposed terraform.tfstate',
    ),
    'route-users-csv' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'pii',
        2 => 'credentials',
      ),
      'name' => 'Exposed users.csv',
    ),
    'route-sql-backup' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'database',
        2 => 'backup',
      ),
      'name' => 'Exposed SQL backup',
    ),
    'route-dotaws-listing' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cloud',
        2 => 'aws',
        3 => 'directory-listing',
      ),
      'name' => 'Exposed .aws directory listing',
    ),
    'route-aws-cli-credentials' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cloud',
        2 => 'aws',
        3 => 'credentials',
      ),
      'name' => 'Exposed AWS CLI credentials',
    ),
    'route-aws-cli-config' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'cloud',
        2 => 'aws',
        3 => 'config',
      ),
      'name' => 'Exposed AWS CLI config',
    ),
    'route-phpmyadmin' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'panel',
        2 => 'exposure',
      ),
      'name' => 'phpMyAdmin login',
    ),
    'route-phpmyadmin-css' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'panel',
        2 => 'asset',
      ),
      'name' => 'phpMyAdmin theme stylesheet',
    ),
    'route-ai-claude-json' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Claude Code config (.claude.json)',
    ),
    'route-ai-claude-desktop' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Claude Desktop config',
    ),
    'route-ai-mcp-json' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed editor MCP config',
    ),
    'route-ai-continue' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Continue config',
    ),
    'route-ai-aider' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed aider config',
    ),
    'route-ai-copilot-token' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed Copilot token endpoint',
    ),
    'route-ai-openai-models' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'config-disclosure',
        3 => 'appliance',
      ),
      'name' => 'Exposed OpenAI-compatible models list',
    ),
    'route-mcp-endpoint' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'mcp',
        3 => 'appliance',
      ),
      'name' => 'MCP Streamable-HTTP endpoint',
    ),
    'route-llm-auth' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'ai-config',
        2 => 'llm-gateway',
        3 => 'appliance',
      ),
      'name' => 'LLM gateway auth required',
    ),
    'route-ai-ollama-version' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'ai-recon',
        1 => 'exposure',
        2 => 'appliance',
      ),
      'name' => 'Exposed Ollama server version',
    ),
    'route-config-php' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed application config (config.php)',
    ),
    'route-envfile-prod' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.production)',
    ),
    'route-secrets-json' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed secrets.json',
    ),
    'route-docker-compose' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed docker-compose.yml',
    ),
    'route-application-properties' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed Spring properties (application.properties)',
    ),
    'route-envfile-local' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'config-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed environment file (.env.local)',
    ),
    'route-wp-debug-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed WordPress debug log (debug.log)',
    ),
    'route-php-error-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed PHP error log (error_log)',
    ),
    'route-laravel-log-alt' => 
    array (
      'sev' => 'high',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'secrets',
      ),
      'name' => 'Exposed Laravel log (laravel.log)',
    ),
    'route-nginx-error-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed nginx error log (error.log)',
    ),
    'route-nginx-access-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed nginx access log (access.log)',
    ),
    'route-apache-error-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed Apache error log (error.log)',
    ),
    'route-apache-access-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed Apache access log (access.log)',
    ),
    'route-app-log' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed application log (app.log)',
    ),
    'route-catalina-out' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'log-disclosure',
        2 => 'information-disclosure',
      ),
      'name' => 'Exposed Tomcat log (catalina.out)',
    ),
    'route-swagger-json-doc' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'openapi',
        3 => 'discovery',
      ),
      'name' => 'Exposed OpenAPI/Swagger document',
    ),
    'route-swagger2-apidocs' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'swagger',
        3 => 'discovery',
      ),
      'name' => 'Exposed Swagger 2.0 document',
    ),
    'route-swagger-yaml-doc' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'openapi',
        3 => 'discovery',
      ),
      'name' => 'Exposed OpenAPI document (YAML)',
    ),
    'route-swagger-ui-html' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'swagger-ui',
        3 => 'discovery',
      ),
      'name' => 'Exposed Swagger UI',
    ),
    'route-wp-json' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'wordpress',
        3 => 'discovery',
      ),
      'name' => 'Exposed WordPress REST API index',
    ),
    'route-api-v2' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'exposure',
        1 => 'api',
        2 => 'discovery',
      ),
      'name' => 'Exposed REST API index (/api/v2)',
    ),
    'route-phpmyadmin-changelog' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'version',
        2 => 'disclosure',
      ),
      'name' => 'phpMyAdmin ChangeLog (version disclosure)',
    ),
    'route-phpmyadmin-readme' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'version',
        2 => 'disclosure',
      ),
      'name' => 'phpMyAdmin README (version disclosure)',
    ),
    'route-phpmyadmin-doc' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'phpmyadmin',
        1 => 'version',
        2 => 'disclosure',
      ),
      'name' => 'phpMyAdmin documentation (version disclosure)',
    ),
    'route-grafana-health' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'grafana',
        1 => 'health',
        2 => 'version',
        3 => 'disclosure',
      ),
      'name' => 'Grafana health (version disclosure)',
    ),
    'route-grafana-login' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'grafana',
        1 => 'panel',
        2 => 'login',
        3 => 'exposure',
      ),
      'name' => 'Grafana login',
    ),
    'route-jenkins-apijson' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'jenkins',
        1 => 'api',
        2 => 'version',
        3 => 'disclosure',
      ),
      'name' => 'Jenkins API root (version disclosure)',
    ),
    'route-pgadmin-login' => 
    array (
      'sev' => 'info',
      'tags' => 
      array (
        0 => 'pgadmin',
        1 => 'panel',
        2 => 'login',
        3 => 'exposure',
      ),
      'name' => 'pgAdmin 4 login',
    ),
    'route-cpanel-login' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'cpanel',
        1 => 'panel',
        2 => 'login',
        3 => 'exposure',
      ),
      'name' => 'cPanel login',
    ),
    'route-whm-login' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'whm',
        1 => 'cpanel',
        2 => 'panel',
        3 => 'login',
        4 => 'exposure',
      ),
      'name' => 'WHM login',
    ),
    'route-phppgadmin-intro' => 
    array (
      'sev' => 'low',
      'tags' => 
      array (
        0 => 'phppgadmin',
        1 => 'postgres',
        2 => 'panel',
        3 => 'version',
        4 => 'disclosure',
      ),
      'name' => 'phpPgAdmin intro (version disclosure)',
    ),
    'route-phpinfo' => 
    array (
      'sev' => 'medium',
      'tags' => 
      array (
        0 => 'recon',
        1 => 'phpinfo',
        2 => 'exposure',
      ),
      'name' => 'PHP info page disclosure',
    ),
  ),
  'routes' => 
  array (
    'GET /api/ps' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"models"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-ollama-ps',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-ollama-ps',
        ),
        'w' => 1000,
      ),
    ),
    'GET /api/tags' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"models"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-ollama-tags',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-ollama-tags',
        ),
        'w' => 1000,
      ),
    ),
    'GET /private/' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'Authorization Required',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-basic-auth',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-basic-auth',
        ),
        'th' => 
        array (
          'WWW-Authenticate' => 
          array (
            0 => 'Basic realm=',
          ),
        ),
      ),
    ),
    'GET /credentials.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /creds.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /backup/credentials.txt' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-credentials-txt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-credentials-txt',
        ),
      ),
    ),
    'GET /terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /.terraform/terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /infra/terraform.tfstate' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"terraform_version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-terraform-tfstate',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-terraform-tfstate',
        ),
      ),
    ),
    'GET /users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /export/users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /backup/users.csv' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'password_hash',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-users-csv',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-users-csv',
        ),
      ),
    ),
    'GET /backup.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /database.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /dump.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /db_backup.sql' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'CREATE TABLE',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-sql-backup',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-sql-backup',
        ),
      ),
    ),
    'GET /.aws' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Index of',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-dotaws-listing',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-dotaws-listing',
        ),
      ),
    ),
    'GET /.aws/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Index of',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-dotaws-listing',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-dotaws-listing',
        ),
      ),
    ),
    'GET /.aws/credentials' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'aws_access_key_id',
          1 => 'aws_secret_access_key',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-aws-cli-credentials',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-aws-cli-credentials',
        ),
        'w' => 1000,
      ),
    ),
    'GET /.aws/config' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[default]',
          1 => 'output = json',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-aws-cli-config',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-aws-cli-config',
        ),
        'w' => 1000,
      ),
    ),
    'GET /phpmyadmin/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpMyAdmin/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /pma/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpmyadmin/index.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin',
        ),
      ),
    ),
    'GET /phpmyadmin/phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /phpMyAdmin/phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /pma/phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /phpmyadmin.css.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'loginform',
          1 => 'pma-card',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-css',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-css',
        ),
      ),
    ),
    'GET /.claude.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-claude-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-claude-json',
        ),
      ),
    ),
    'GET /claude_desktop_config.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-claude-desktop',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-claude-desktop',
        ),
      ),
    ),
    'GET /.cursor/mcp.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-mcp-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-mcp-json',
        ),
      ),
    ),
    'GET /.vscode/mcp.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'mcpServers',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-mcp-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-mcp-json',
        ),
      ),
    ),
    'GET /.continue/config.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"models"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-continue',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-continue',
        ),
      ),
    ),
    'GET /.aider.conf.yml' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'anthropic-api-key',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-aider',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-aider',
        ),
      ),
    ),
    'GET /copilot_internal/v2/token' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'annotations_enabled',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-copilot-token',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-copilot-token',
        ),
      ),
    ),
    'GET /openai/models' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"object":"list"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-openai-models',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-openai-models',
        ),
      ),
    ),
    'GET /mcp' => 
    array (
      0 => 
      array (
        's' => 400,
        'bw' => 
        array (
          0 => 'jsonrpc',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-mcp-endpoint',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-mcp-endpoint',
        ),
      ),
    ),
    'GET /api/mcp' => 
    array (
      0 => 
      array (
        's' => 400,
        'bw' => 
        array (
          0 => 'jsonrpc',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-mcp-endpoint',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-mcp-endpoint',
        ),
      ),
    ),
    'GET /v1/chat' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'invalid_request_error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-llm-auth',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-llm-auth',
        ),
      ),
    ),
    'GET /v1/completions' => 
    array (
      0 => 
      array (
        's' => 401,
        'bw' => 
        array (
          0 => 'invalid_request_error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-llm-auth',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-llm-auth',
        ),
      ),
    ),
    'GET /api/version' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"version"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-ai-ollama-version',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-ai-ollama-version',
        ),
        'w' => 1000,
      ),
    ),
    'GET /config.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'DB_PASSWORD',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-config-php',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-config-php',
        ),
      ),
    ),
    'GET /.env.production' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-prod',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-prod',
        ),
      ),
    ),
    'GET /secrets.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'secretKey',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-secrets-json',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-secrets-json',
        ),
      ),
    ),
    'GET /docker-compose.yml' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'services:',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-docker-compose',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-docker-compose',
        ),
      ),
    ),
    'GET /application.properties' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'spring.datasource',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-application-properties',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-application-properties',
        ),
      ),
    ),
    'GET /.env.local' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'AWS_SECRET_ACCESS_KEY',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-envfile-local',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-envfile-local',
        ),
      ),
    ),
    'GET /wp-content/debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Notice',
          1 => 'PHP Warning',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-debug-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-debug-log',
        ),
      ),
    ),
    'GET /wp-content/uploads/debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Notice',
          1 => 'PHP Warning',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-debug-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-debug-log',
        ),
      ),
    ),
    'GET /debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Notice',
          1 => 'PHP Warning',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-debug-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-debug-log',
        ),
      ),
    ),
    'GET /error_log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /php_errors.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /php_error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /logs/error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'PHP Fatal error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-php-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-php-error-log',
        ),
      ),
    ),
    'GET /laravel.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'production.ERROR',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-laravel-log-alt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-laravel-log-alt',
        ),
      ),
    ),
    'GET /logs/laravel.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'production.ERROR',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-laravel-log-alt',
        'sev' => 'high',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-laravel-log-alt',
        ),
      ),
    ),
    'GET /var/log/nginx/error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[error]',
          1 => 'upstream',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nginx-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-nginx-error-log',
        ),
      ),
    ),
    'GET /nginx_error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[error]',
          1 => 'upstream',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nginx-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-nginx-error-log',
        ),
      ),
    ),
    'GET /var/log/nginx/access.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"GET /',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-nginx-access-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-nginx-access-log',
        ),
      ),
    ),
    'GET /var/log/apache2/error.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[core:error]',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-apache-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-apache-error-log',
        ),
      ),
    ),
    'GET /var/log/httpd/error_log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '[core:error]',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-apache-error-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-apache-error-log',
        ),
      ),
    ),
    'GET /var/log/apache2/access.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"GET /',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-apache-access-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-apache-access-log',
        ),
      ),
    ),
    'GET /app.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /logs/app.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /server.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /logs/debug.log' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'ERROR',
          1 => 'level=error',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-app-log',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-app-log',
        ),
      ),
    ),
    'GET /catalina.out' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'SEVERE',
          1 => 'java.lang.',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-catalina-out',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-catalina-out',
        ),
      ),
    ),
    'GET /swagger.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /api/swagger.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /v3/api-docs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /api-docs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /.well-known/openapi.json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"openapi":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-json-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-json-doc',
        ),
      ),
    ),
    'GET /v2/api-docs' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => '"swagger":',
          1 => '"paths"',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger2-apidocs',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger2-apidocs',
        ),
      ),
    ),
    'GET /openapi.yaml' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'openapi:',
          1 => 'paths:',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-yaml-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-yaml-doc',
        ),
      ),
    ),
    'GET /swagger-ui.html' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /swagger-ui/index.html' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /swagger' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /api/__swagger__/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'swagger-ui',
          1 => 'SwaggerUIBundle',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-swagger-ui-html',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-swagger-ui-html',
        ),
      ),
    ),
    'GET /wp-json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'namespaces',
          1 => 'routes',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-wp-json',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-wp-json',
        ),
      ),
    ),
    'GET /api/v2' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'endpoints',
          1 => 'version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-api-v2',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-api-v2',
        ),
      ),
    ),
    'GET /phpmyadmin/ChangeLog' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
          1 => 'ChangeLog',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-changelog',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-changelog',
        ),
      ),
    ),
    'GET /phpmyadmin/README' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-readme',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-readme',
        ),
      ),
    ),
    'GET /phpmyadmin/doc/html/index.html' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpMyAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpmyadmin-doc',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpmyadmin-doc',
        ),
      ),
    ),
    'GET /api/health' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'commit',
          1 => 'version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-health',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-health',
        ),
      ),
    ),
    'GET /grafana/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Grafana',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-login',
        ),
      ),
    ),
    'GET /grafana/login' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'Grafana',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-grafana-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-grafana-login',
        ),
      ),
    ),
    'GET /api/json' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'jobs',
          1 => 'mode',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-jenkins-apijson',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-jenkins-apijson',
        ),
      ),
    ),
    'GET /pgadmin4/' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'pgAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-pgadmin-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-pgadmin-login',
        ),
      ),
    ),
    'GET /pgadmin4/login' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'pgAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-pgadmin-login',
        'sev' => 'info',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-pgadmin-login',
        ),
      ),
    ),
    'GET /cpanel' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'cPanel',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-cpanel-login',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-cpanel-login',
        ),
      ),
    ),
    'GET /whm' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'WHM',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-whm-login',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-whm-login',
        ),
      ),
    ),
    'GET /phppgadmin/intro.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpPgAdmin',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phppgadmin-intro',
        'sev' => 'low',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phppgadmin-intro',
        ),
      ),
    ),
    'GET /phpinfo.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpinfo()',
          1 => 'PHP Version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpinfo',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpinfo',
        ),
        'w' => 8,
      ),
    ),
    'GET /phpinfo' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpinfo()',
          1 => 'PHP Version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpinfo',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpinfo',
        ),
        'w' => 8,
      ),
    ),
    'GET /info.php' => 
    array (
      0 => 
      array (
        's' => 200,
        'bw' => 
        array (
          0 => 'phpinfo()',
          1 => 'PHP Version',
        ),
        'nf' => 
        array (
        ),
        'pid' => 'route-phpinfo',
        'sev' => 'medium',
        'sig' => 0,
        't' => 
        array (
          0 => 'route-phpinfo',
        ),
        'w' => 8,
      ),
    ),
  ),
);
